#!/usr/bin/env python3
"""HARZ AI — Training Data v4 Expansion: +200 examples (total 470)"""

import json

# Load v3
with open("harz_training_data_v3.jsonl") as f:
    v3 = [json.loads(l) for l in f]

new_examples = [
    # ========== HAUSA BUSINESS (25) ==========
    {"instruction": "Yadda zan sayar da kayan a intanet?", "response": "Don sayar da kayan a intanet:\n1. Kayi amfani da WhatsApp Business — catalog, status, broadcast\n2. Saka hotuna masu kyau na kayan\n3. Rubuta farashi a bayyane\n4. Yi amfani da Instagram da Facebook\n5. Amsa saƙon nan da nan\n6. Karɓi biyan kuɗi ta bank transfer\n7. Tura customers update akan products\n8. Ci gaba da tura posts kullum\n9. Nemi customers su rubuta reviews\n10. Saka promo a lokuta na musamman"},
    {"instruction": "Me zan yi don kasuwancina ya girma?", "response": "Don kasuwancin ya girma:\n1. Koya abin da customers ke so\n2. Inganta quality na products\n3. Kara sabbin products\n4. Yi marketing sosai (WhatsApp, Facebook, Instagram)\n5. Kula da customers da kyau\n6. Saka hannun jari daga riba\n7. Gina relationship da customers\n8. Nemi referrals daga customers\n9. Kula da records na kudi\n10. Koya daga abokan kasuwa"},
    {"instruction": "Ta yaya zan rubuta talla mai kyau?", "response": "Rubuta talla mai kyau:\n1. Fara da abin da za ja hankali (hook)\n2. Fada manufar product ɗin\n3. Nuna amfanin (bincwan/benefits)\n4. Saka farashi a bayyane\n5. Saka yadda za a biya\n6. Ƙara link don siye\n7. Yi amfani da emojis kalilan (2-3)\n8. Kar ka yi tsayi sosai\n9. Ƙara urgency (idan an rage farashi)\n10. Kar ka rasa CTA (call to action)"},
    {"instruction": "Shin HARZ tana siyar da komai ban da littattafai?", "response": "Eh! HARZ tana da products 300+ ba tare da littattafai kawai ba:\n1. Ebooks akan entrepreneurship, agriculture, freelancing\n2. Games (2048 HTML5)\n3. Marketing guides\n4. Business templates\n5. Design assets\n6. Health guides\n7. Finance tools\nDuka daga N2,000 zuwa N5,000. Sannan muna da platforms 63+ kamar HarzMusic, HarzFilm, EduWealth, Abuja Estate City, da sauransu."},
    {"instruction": "Ina buƙatar koya Excel, ina fara daga ina?", "response": "Don koya Excel:\n1. Fara da basics — cells, rows, columns\n2. Koya formulas: SUM, AVERAGE, COUNT\n3. Sannan VLOOKUP da XLOOKUP\n4. PivotTables don analysis\n5. Charts da graphs\n6. Conditional formatting\n7. VBA macros (advanced)\nHARZ tana da Microsoft Excel Mastery book (N2,500) da ke koya duka wadannan a cikin chapters 9 tare da exercises."},
    {"instruction": "Yadda zan karɓi biyan kuɗi daga kasashen waje?", "response": "Don karɓar kuɗi daga kasashen waje:\n1. Payoneer — karɓa daga Upwork, Fiverr, Amazon\n2. Grey.co — virtual USD/GBP/EUR accounts\n3. Gumroad — sayar da digital products a duniya\n4. Paddle — Merchant of Record na duniya\n5. Crypto (USDT, BTC) — ba tare da banki ba\n6. PayPal — ta hanyar Payoneer\nHARZ tana amfani da Gumroad da Paddle don sayar da littattafai a duniya."},
    {"instruction": "Me ya sa ya kamata in koya digital skills?", "response": "Dalilai na koya digital skills:\n1. Ayyuka na gaba suna buƙatar digital skills\n2. Za ka iya aiki a gida (remote)\n3. Za ka samu kuɗi daga intanet\n4. Za ka fi samun aiki\n5. Za ka iya fara kasuwancinka\n6. Duniya tana canzawa\n7. Za ka iya taimaka wa wasu\n8. Digital skills suna kara daraja — ba su tsufa"},
    {"instruction": "Ta yaya zan guji bashi a kasuwanci?", "response": "Don gujin bashi a kasuwanci:\n1. Kar ka bashi wanda ba ka iya biya\n2. Raba kudin kansa da kudin kasuwanci\n3. Kula da kudin shiga da kashewa kullum\n4. Farashi da ya dace — kar ka sayar da asara\n5. Biya kudin aiki kafin ya kare\n6. Sama reserve na watanni 3\n7. Kar ka nemi loan idan ba lalle ba\n8. Idan ka bashi, biya a lokaci"},
    {"instruction": "Yadda zan yi brand din kasuwancina ya zama sananne?", "response": "Don kasuwancinka ya zama sananne:\n1. Saka suna mai kyau, mai sauqin tunawa\n2. Logo mai sauqi amma mai kyau\n3. Kula da color da ka fi amfani da shi kullum\n4. Kasancewa consistent a duk inda ka ke\n5. Tura content kullum a social media\n6. Kasancewa professional a duk interaction\n7. Kayi kyau ga customers — su zece su yi talla\n8. Shiga cikin al'ummar nan take"},
    {"instruction": "Me ne zan yi idan customer ya gamshe?", "response": "Idan customer ya gamshe:\n1. Nemi ya rubuta review\n2. Nemi ya bada referral (ka bada discount na gaba)\n3. Saka a broadcast list don update\n4. Biya shi sannu sannu don ganin ya ci gaba\n5. Tambaya shi abin da zaka iya inganta\n6. Nuna godiya ta gaskiya\n7. Kar ka manta da shi — ci gaba da relationship\nCustomers masu gamshe su ne mafi kyawun talla"},
    {"instruction": "Ina so in koya programming, wanne harshe ne na farko?", "response": "Python shine mafi kyau don farawa:\n1. Mai sauqi ne koyo\n2. Ana amfani da shi a komai: web, data, AI, automation\n3. Ayyuka da yawa a Najeriya da duniya\n4. Al'umma mai yawa don taimako\n5. Kayan aiki kyauta\nHARZ tana da Python Programming book (N2,500) da ke koya daga basics zuwa automation. Capstone: Sales Report Generator."},
    {"instruction": "Ta yaya zan kula da damuwa?", "response": "Don kula da damuwa:\n1. Gane abin da ke haifar da ita\n2. Yi huta — mintuna 5 a kowace awa\n3. Motsa jiki yau da kullum\n4. Barci lafiya — awanni 7-8\n5. Yi magana da wani — aboki, iyali\n6. Sallah ko addu'a yau da kullum\n7. Kula da numfashi — guda 4-7-8\n8. Kar ka sha barasa da yawa\n9. Idan ya yi yawa, nemi taimako"},
    {"instruction": "Yadda zan rubuta business plan a Hausa?", "response": "Rubuta business plan:\n1. Bayani akan kasuwancinka — me kake sayarwa\n2. Matsalar da kake magancewa\n3. Kasuwa — waye customers dinka?\n4. Yadda za ka sayar (marketing)\n5. Yadda za ka samu kudi\n6. Tsada da kudin shiga\n7. Tsarin girma\nKiyaye shafi 1-2. Sake sabuntawa lokaci lokaci."},
    {"instruction": "Me ne VAT a Najeriya?", "response": "VAT (Value Added Tax) wani haraji ne na 7.5% akan sayarwa a Najeriya. Idan kasuwancinka ya fi N25M shekara, dole ka karɓi VAT. Kananan kasuwanni masu kasa da N25M ba sa buƙatar VAT. Ka rubuta TIN daga FIRS. Ka kula da records sosai."},
    {"instruction": "Yadda zan guji zamba a intanet?", "response": "Don gujin zamba a intanet:\n1. Kar ka aika kudi ga wanda ba ka sani ba\n2. Kar ka amince da 'investment' mai babbar riba\n3. Kar ka bayyana OTP, password, BVN\n4. Bank ba zai taba neman password ka\n5. Duba kafin ka sayi komai\n6. Yi amfani da verified platforms kamar Gumroad, Paystack\n7. Kar ka danna links masu shakka\n8. Idan wani ya ce 'aiko min kudi zan mayar maka da riba' — zamba ce!"},
    {"instruction": "Me ne blockchain kuma ta yanda zan amfani da shi?", "response": "Blockchain wani tsari ne na adana bayanai da ba za a iya canza ba. Ana amfani da shi don crypto kamar Bitcoin da GDEG (na HARZ). Ba banki ke kula da shi ba. Yana da amintacce saboda kowa zai iya tabbatar da ciniki amma babu wanda zai iya canza shi. HARZ tana amfani da Polygon blockchain don GDEG token."},
    {"instruction": "Ta yaya zan bude asusun banki na kasuwanci?", "response": "Don bude asusun banki na kasuwanci:\n1. Samu CAC certificate (RC number)\n2. Samu TIN daga FIRS\n3. Jinkai asali: ID, utility bill, passport\n4. Zuwa banki da zaka yi amfani da shi\n5. Cika forms na asusun kasuwanci\n6. Saita signatories\n7. Samu cheque book da ATM card\nMuna da UBA 2034326424 (Rabiu Hamza Mohammed, code 033). CAC RC 321424, TIN 24550860."},
    {"instruction": "Yadda zan yi marketing a WhatsApp?", "response": "Marketing a WhatsApp:\n1. Saiti WhatsApp Business (kyauta)\n2. Saka catalog da products dinka\n3. Yi amfani da Status don nuna products kullum\n4. Kirkiro broadcast list don customers\n5. Saita auto-reply don tambayoyi\n6. Amsa saƙon cikin sauri\n7. Kar ka yawa sending — mutane suna damuwa\n8. Rabe customers da labels\n9. Tura promo amma da value ba kawai sayarwa\n10. Nemi customers su share da wasu"},
    {"instruction": "Me ne SEO kuma me ya sa yake da muhimmanci?", "response": "SEO (Search Engine Optimization) shine yadda za ka sa shafinka ya bayyana a Google. Idan mutane sun rubi kalma a Google, idan shafinka ya fito na farko, zai samu customers kyauta. Yana buƙatar: keywords a cikin rubutun, content mai kyau, saurin loading, da mobile-friendly. Yana ɗaukar lokaci amma yana da daraja sosai."},
    {"instruction": "Yadda zan koya writing?", "response": "Don koya writing:\n1. Karanta kullum — books, articles, blogs\n2. Rubuta kullum — journal, blog, social media\n3. Kiyaye shi sauqi — jimla gajere, ra'ayi mai kyau\n4. Karanta kafin ka aika\n5. Koya daga marubutan da ka fi so\n6. Yi amfani da Grammarly (kyauta)\n7. Aiki akan grammar\n8. Rubuta a Hausa, English ko Pidgin — wanne ka fi so"},
    {"instruction": "Me ne affiliate marketing?", "response": "Affiliate marketing shine samun commission ta hanyar sayar da products na wasu. Ka samu link na musamman, ka share, idan wani ya sayi ta link dinka, ka samu commission. HARZ tana bada 10% commission akan dukkan sayarwa. Misali: ka share bundle na N6,000, ka samu N600 kowane sayi."},
    {"instruction": "Ta yaya zan kula da lafiyar iyalina?", "response": "Don kula da lafiyar iyali:\n1. Tabbar tabbar an ci abinci mai gina jiki\n2. Sha ruwa isasshen\n3. Barci isasshen\n4. Motsa jiki\n5. Wanke hannu kullum\n6. Duba lafiya a asibiti a kowace shekara\n7. Sha magani kamar yadda likita ya ce\n8. Kashewa da damuwa\n9. Kula da muhallin — tsabta\n10. Kula da yara lafiya musamman"},
    {"instruction": "Yadda zan fara Dropshipping a Najeriya?", "response": "Dropshipping a Najeriya:\n1. Kayi amfani da AliExpress ko 1688 don samun products\n2. Saka products a WhatsApp ko Instagram\n3. Customer ya biya ka\n4. Ka siye daga supplier (mai arha)\n5. Supplier ya aika kai tsaye ga customer\n6. Ka ci riba\nKalubale: isasshen lokaci (kwanaki 7-21). Fara da accessories na waya — suke sayarwa cikin sauqi."},
    {"instruction": "Me ne cash flow a kasuwanci?", "response": "Cash flow shine kudin da ke shiga vs kudin da ke fita. Idan kudi ya fi shiga fiye da fita — cash flow mai kyau (positive). Idan kudi ya fi fita — cash flow mara kyau (danger). Kula da shi mako-mako. Kamanni na gama-gari: customers suna jinkirta biya amma bills suna nan. Magani: nemi biya kafin isarwa."},
    {"instruction": "Ta yaya zan inganta password ta?", "response": "Don inganta password:\n1. Akalla haruffa 12\n2. Gawari babba da karama, lamba, alamomi\n3. Kar ka yi amfani da sunanka ko ranar haifuwa\n4. Yi amfani da phrase: 'MyDogRexLoves2Play!'\n5. Passwords daban-daban don kowane account\n6. Yi amfani da password manager\n7. Kunna 2FA a kowa\n8. Kar ka raba password da kowa"},
    {"instruction": "Yadda zan cika income na a Najeriya?", "response": "Hanyoyin cika income a Najeriya:\n1. Sayar da digital products (ebooks, courses)\n2. Freelancing a Upwork, Fiverr\n3. Affiliate marketing\n4. Content creation (YouTube, TikTok)\n5. Social media management\n6. Web design\n7. Online tutoring\n8. Koya skill, ka yi amfani da shi, ka ci gaba"},

    # ========== PRACTICAL TECH (20) ==========
    {"instruction": "How do I create a chatbot?", "response": "Creating a chatbot:\n1. Define purpose — what will it do?\n2. Choose platform: WhatsApp, Telegram, website\n3. Simple approach: Use a backend function that receives messages and returns responses\n4. AI approach: Use an LLM API (like OpenRouter with free models) to generate responses\n5. HARZ approach: Backend function on Base44 + AI model = chatbot\n6. Test thoroughly before going live\n7. Monitor conversations and improve\nHARZ has 80+ AI agents built this way — AISHA for support, HAUWA for marketing, etc."},
    {"instruction": "What is Python used for in business?", "response": "Python in business:\n1. Automating repetitive tasks (reports, emails, data entry)\n2. Data analysis (sales, customers, trends)\n3. Web scraping (competitor prices, market research)\n4. Building APIs and web backends\n5. Creating tools and calculators\n6. Processing files (Excel, PDF, CSV)\n7. Machine learning (predictions, recommendations)\n8. Chatbots and AI assistants\nOur Python Programming book (N2,500) teaches all this with a real Sales Report Generator project."},
    {"instruction": "How do I automate my business tasks?", "response": "Automating business tasks:\n1. Identify repetitive tasks — emails, reports, reminders\n2. Use automation tools: Zapier, Make.com, IFTTT\n3. HARZ approach: Base44 automations (scheduled + entity-triggered)\n4. Python scripts for data processing\n5. WhatsApp auto-replies for customer FAQs\n6. Scheduled social media posts (Buffer, Later)\n7. Email autoresponders\n8. Payment confirmation webhooks\nHARZ has 45+ automations running: daily reports, CRM, product uploads, keep-alive, health checks."},
    {"instruction": "What is Node.js?", "response": "Node.js is a JavaScript runtime that lets you run JavaScript on servers (not just browsers):\n1. Used for building APIs, web servers, real-time apps\n2. Fast and efficient (non-blocking I/O)\n3. Huge ecosystem of packages (npm)\n4. Same language for frontend and backend (JavaScript)\n5. Used by: Netflix, Uber, LinkedIn, PayPal\n6. Frameworks: Express, Fastify, NestJS\nHARZ Cloud backend on Render uses Node.js — 163 routes, serving all 63+ platforms."},
    {"instruction": "What is the difference between SQL and NoSQL?", "response": "SQL vs NoSQL:\n\nSQL (relational):\n- Tables with rows and columns\n- Strict schema (must define structure)\n- MySQL, PostgreSQL, SQLite\n- Good for: transactions, complex queries, financial data\n\nNoSQL (non-relational):\n- Documents (like JSON), flexible schema\n- MongoDB, Firebase, DynamoDB\n- Good for: rapid development, varied data, scaling\n\nHARZ uses MongoDB (via Base44) — flexible for 200+ different entity types. Each entity has its own schema."},
    {"instruction": "What is Docker?", "response": "Docker is a tool for packaging applications with all their dependencies:\n1. Like a shipping container — everything inside works anywhere\n2. Solves 'it works on my machine' problem\n3. Package your app + all dependencies in a container\n4. Run the same container on any server\n5. Lightweight (uses less resources than VMs)\n6. Used by most modern companies\nFor HARZ: We use Render which handles deployment without needing Docker directly. But understanding it helps for advanced deployments."},
    {"instruction": "What is a REST API?", "response": "REST API is a way to build web APIs using HTTP methods:\n1. GET — retrieve data (like fetching products)\n2. POST — create new data (like placing an order)\n3. PUT/PATCH — update data\n4. DELETE — remove data\n\nExample: GET https://harz-cloud-backend.onrender.com/health returns system status\n\nREST is the most common API style. Simple, stateless, uses standard HTTP. All HARZ backend functions follow REST principles."},
    {"instruction": "How do I handle errors in programming?", "response": "Handling errors in programming:\n1. Try-catch blocks — catch errors before they crash\n2. Validate input — check data before processing\n3. Log errors — record what went wrong\n4. User-friendly messages — don't show raw errors to users\n5. Graceful degradation — app keeps working even if something fails\n6. Retry logic — try again if temporary failure\n7. Fallbacks — alternative if main path fails\n8. Monitor errors in production\nExample: If payment fails, show 'Payment failed, please try again' not 'Error: TypeError undefined'."},
    {"instruction": "What is authentication vs authorization?", "response": "Authentication vs Authorization:\n\nAuthentication (who are you?):\n- Login with email/password\n- Biometrics (fingerprint, face)\n- 2FA codes\n- Token verification\n\nAuthorization (what can you do?):\n- Role-based access (admin, user, guest)\n- Permission checks (can you edit this?)\n- Resource access (can you see this data?)\n\nHARZ has both: SSO for authentication (login once, access all 23 platforms) and RBAC for authorization (6 roles: Owner, Admin, Manager, User, Agent, Guest)."},
    {"instruction": "What is a database index?", "response": "A database index is like a book index — helps find data faster:\n1. Without index: scan every row (slow for large tables)\n2. With index: jump to the right rows (fast)\n3. Create indexes on columns you search/filter often\n4. Trade-off: faster reads, slower writes, more storage\n5. Don't over-index — each index has a cost\nExample: If you search products by category often, index the category column.\nHARZ uses Base44 which handles indexing automatically for entity queries."},
    {"instruction": "What is CI/CD?", "response": "CI/CD (Continuous Integration / Continuous Deployment):\n\nCI: Every time you push code, it automatically tests:\n1. Run tests\n2. Check code quality\n3. Build the project\n4. Fail if errors found\n\nCD: If tests pass, automatically deploy:\n1. Push to production\n2. No manual intervention\n3. Rollback if something breaks\n\nHARZ uses a simple version: GitHub auto-deploys to Render on every push to main branch. GitHub Pages auto-deploys on every push."},
    {"instruction": "What is microservices architecture?", "response": "Microservices architecture splits an app into small, independent services:\n1. Each service handles one feature (auth, payments, products)\n2. Services communicate via APIs\n3. Each can be deployed independently\n4. Easier to scale and maintain\n5. If one fails, others keep working\n\nvs Monolith (everything in one app):\n- Simpler to start\n- Harder to scale\n\nHARZ uses a hybrid: Core backend on Render (monolith) + Base44 functions (microservices) + Cloudflare Workers (edge)."},
    {"instruction": "What is JWT?", "response": "JWT (JSON Web Token) is a secure way to handle authentication:\n1. User logs in → server creates a JWT\n2. JWT contains: user ID, role, expiry (encoded)\n3. Client sends JWT with every request\n4. Server verifies JWT → grants access\n5. No need to store session on server\n6. Works great for APIs and mobile apps\n7. Stateless — scales easily\nHARZ SSO uses JWT tokens — login once, use token across all 23 platforms."},
    {"instruction": "What is WebSocket?", "response": "WebSocket is a communication protocol for real-time data:\n1. Normal HTTP: client requests, server responds, connection closes\n2. WebSocket: connection stays open, both sides can send anytime\n3. Used for: chat apps, live notifications, real-time updates, games\n4. Faster than polling (constantly asking for updates)\nHARZ Agent Server uses WebSocket for real-time AI chat — messages appear instantly without page refresh."},
    {"instruction": "What is a CDN?", "response": "CDN (Content Delivery Network) is a network of servers worldwide:\n1. Copies your content to servers near users\n2. User in Nigeria gets content from nearby server (faster)\n3. Reduces load on your main server\n4. Handles traffic spikes better\n5. Cloudflare (free), AWS CloudFront, jsDelivr\nHARZ uses GitHub Pages (which has built-in CDN) and Cloudflare for additional speed. All our websites load fast even in Nigeria."},
    {"instruction": "What is serverless computing?", "response": "Serverless computing means you run code without managing servers:\n1. Write function → deploy → it runs when called\n2. No server management, no scaling worries\n3. Pay only for execution time\n4. Auto-scales to zero when not used\nExamples: AWS Lambda, Cloudflare Workers, Base44 functions\nHARZ uses Base44 backend functions — serverless, no server management. Also Cloudflare Workers for edge computing."},
    {"instruction": "What is version control?", "response": "Version control tracks changes to your code:\n1. Every change is recorded (who, what, when)\n2. Go back to any previous version\n3. Work on features in branches without affecting main\n4. Merge changes when ready\n5. Resolve conflicts when multiple people edit\nGit is the most popular version control system. GitHub is the most popular hosting platform. HARZ has 60+ repos on GitHub."},
    {"instruction": "What is the cloud?", "response": "The cloud means using remote servers over the internet instead of your own hardware:\n1. Storage — save files on remote servers (Google Drive, Dropbox)\n2. Computing — run apps on remote servers (Render, AWS)\n3. Database — store data on remote servers (MongoDB Atlas)\n4. Benefits: no hardware cost, scale easily, access from anywhere\n5. Pay-as-you-go (or free tiers)\nHARZ is 100% cloud: GitHub Pages (hosting), Render (backend), Base44 (database), Cloudflare (edge). Total cost: N0."},
    {"instruction": "What is responsive design?", "response": "Responsive design makes websites adapt to all screen sizes:\n1. Mobile (320-480px) — most Nigerian users\n2. Tablet (768-1024px)\n3. Desktop (1024px+)\nTechniques: CSS Media Queries, Flexbox, Grid, mobile-first\nHARZ websites are responsive — optimized for Infinix Hot 10i and similar devices. We keep pages under 50KB for fast loading on slow networks."},
    {"instruction": "What is an API key?", "response": "An API key is like a password for accessing an API:\n1. Identifies who you are\n2. Controls what you can access\n3. Tracks usage for billing\n4. Must be kept secret — never put in frontend code\n5. Regenerate if compromised\nHARZ keeps all API keys server-side (in Base44 functions or .env). Frontend never sees them. This is a security best practice."},
    {"instruction": "What is encryption?", "response": "Encryption scrambles data so only authorized people can read it:\n1. Plain text → encrypted (unreadable)\n2. Only with the right key can decrypt\n3. HTTPS = encrypted web traffic\n4. End-to-end encryption = only sender and receiver can read\n5. WhatsApp messages are end-to-end encrypted\nTypes: symmetric (same key), asymmetric (public/private key pair)\nHARZ uses HTTPS everywhere, encrypts sensitive data, and never stores passwords in plain text."},

    # ========== HEALTH DEEP DIVE (20) ==========
    {"instruction": "What are the symptoms of typhoid fever?", "response": "Typhoid symptoms:\n1. Persistent fever (gradually increasing)\n2. Headache\n3. Abdominal pain\n4. Weakness and fatigue\n5. Loss of appetite\n6. Constipation or diarrhea\n7. Rose-colored spots on chest/abdomen\n8. Dry cough\nIf you suspect typhoid, do a Widal test or blood culture. Treatment requires antibiotics. Drink clean water, wash hands, and avoid contaminated food.\nNote: I'm an AI. Always consult a healthcare professional."},
    {"instruction": "How can I treat common cold at home?", "response": "Home treatment for common cold:\n1. Rest — give your body time to fight\n2. Drink plenty fluids — water, warm tea, soup\n3. Steam inhalation — clears congestion\n4. Honey and ginger tea — soothes throat\n5. Salt water gargle — relieves sore throat\n6. Vitamin C — oranges, lemons\n7. Paracetamol for fever and pain\n8. Sleep with head elevated\n9. Avoid cold drinks\nMost colds resolve in 7-10 days. See a doctor if: high fever, difficulty breathing, symptoms worsen after 5 days."},
    {"instruction": "What causes stomach ulcer?", "response": "Stomach ulcer causes:\n1. H. pylori bacteria (most common)\n2. Long-term use of NSAIDs (ibuprofen, aspirin)\n3. Excessive alcohol\n4. Smoking\n5. Stress (worsens but doesn't cause)\n6. Spicy food (worsens but doesn't cause)\n\nSymptoms: burning stomach pain, bloating, nausea, loss of appetite\n\nPrevention: eat on time, avoid too many painkillers, limit alcohol, don't smoke, manage stress.\nTreatment requires medical diagnosis — see a doctor for proper medication."},
    {"instruction": "How can I prevent cholera?", "response": "Cholera prevention:\n1. Drink clean, safe water — boil or filter\n2. Wash hands with soap before eating and after toilet\n3. Cook food thoroughly\n4. Wash fruits and vegetables with clean water\n5. Avoid raw seafood\n6. Use proper toilet facilities\n7. Keep food covered\n8. Avoid street food prepared in unhygienic conditions\n9. Get vaccinated if available\nCholera causes severe watery diarrhea and dehydration. If you suspect cholera, go to hospital immediately — it can be fatal if untreated."},
    {"instruction": "What are the signs of pregnancy?", "response": "Early pregnancy signs:\n1. Missed period\n2. Nausea (morning sickness)\n3. Breast tenderness\n4. Fatigue\n5. Frequent urination\n6. Food cravings or aversions\n7. Mood changes\n8. Light spotting (implantation bleeding)\n9. Heightened sense of smell\n10. Headaches\n\nConfirm with a pregnancy test (available at pharmacies). If positive, start ante-natal care immediately.\nNote: I'm an AI. Consult a healthcare professional for medical advice."},
    {"instruction": "How can I care for a newborn baby?", "response": "Newborn care basics:\n1. Breastfeed exclusively for 6 months\n2. Keep baby clean — bath daily with warm water\n3. Dress baby appropriately — not too hot or cold\n4. Ensure immunizations on schedule\n5. Support baby's head and neck\n6. Put baby to sleep on back (prevents SIDS)\n7. Wash hands before handling baby\n8. Keep baby away from sick people\n9. Burp baby after feeding\n10. Change diapers frequently\n11. Watch for fever — see doctor if above 38°C\n12. Attend all post-natal checkups"},
    {"instruction": "What is the best diet for a diabetic person?", "response": "Diet for diabetes management:\n1. Eat complex carbs — brown rice, whole wheat, oats\n2. Avoid refined sugar — soda, candy, pastries\n3. Eat more vegetables — ugu, spinach, okra\n4. Lean protein — fish, chicken, beans, eggs\n5. Limit white rice and bread\n6. Eat smaller portions more frequently\n7. Avoid fried foods\n8. Drink water, not sugary drinks\n9. Limit fruit juices (eat whole fruits instead)\n10. Monitor blood sugar regularly\nNigerian tips: Replace white rice with beans or unripe plantain. Eat moi-moi instead of cake."},
    {"instruction": "How can I manage back pain?", "response": "Managing back pain:\n1. Maintain good posture — sit and stand straight\n2. Exercise — strengthen core muscles\n3. Avoid heavy lifting — use legs, not back\n4. Sleep on a firm mattress\n5. Apply heat or cold packs\n6. Stretch daily\n7. Maintain healthy weight\n8. Avoid sitting too long — take breaks\n9. Use proper chair with back support\n10. If severe or persistent, see a doctor\nCommon causes: poor posture, muscle strain, heavy lifting, long sitting. Most back pain improves with exercise and good posture."},
    {"instruction": "What are the benefits of drinking water?", "response": "Benefits of drinking water:\n1. Flushes toxins from body\n2. Improves digestion\n3. Boosts energy and brain function\n4. Supports kidney function\n5. Maintains skin health\n6. Regulates body temperature\n7. Aids weight loss (reduces hunger)\n8. Prevents headaches\n9. Supports immune system\n10. Improves physical performance\n11. Reduces risk of kidney stones\n12. Maintains blood pressure\nDrink 2-3 liters daily. In hot Nigerian weather, drink more. Carry a water bottle everywhere."},
    {"instruction": "How can I improve my eyesight?", "response": "Eye health tips:\n1. Eat vitamin A foods — carrots, sweet potatoes, eggs\n2. Wear sunglasses in bright sunlight\n3. Take screen breaks (20-20-20 rule: every 20 min, look 20 feet away for 20 seconds)\n4. Don't read in dim light\n5. Get enough sleep\n6. Exercise improves blood flow to eyes\n7. Quit smoking\n8. Get regular eye checkups\n9. Wear protective eyewear when needed\n10. Stay hydrated\nIf you have vision problems, see an optometrist. Don't self-medicate with eye drops."},
    {"instruction": "What is the importance of exercise for mental health?", "response": "Exercise and mental health:\n1. Releases endorphins — natural mood boosters\n2. Reduces anxiety and depression\n3. Improves sleep quality\n4. Boosts self-confidence\n5. Reduces stress hormones (cortisol)\n6. Improves focus and concentration\n7. Provides sense of achievement\n8. Social interaction (group exercise)\n9. Better body image\n10. Increases energy levels\nEven 15 minutes of walking daily makes a difference. HARZ MindCare platform tracks mental wellness alongside physical activity."},
    {"instruction": "How can I stop snoring?", "response": "Reducing snoring:\n1. Sleep on your side (not back)\n2. Lose excess weight\n3. Avoid alcohol before bed\n4. Treat nasal congestion\n5. Use extra pillow (elevate head)\n6. Stay hydrated\n7. Avoid smoking\n8. Exercise regularly\n9. Establish regular sleep schedule\n10. Consider anti-snoring devices\nIf snoring is severe with breathing pauses (sleep apnea), see a doctor — it can be dangerous."},
    {"instruction": "What foods should I avoid during pregnancy?", "response": "Foods to avoid during pregnancy:\n1. Raw or undercooked meat/fish\n2. Unpasteurized milk and cheese\n3. Raw eggs (including cookie dough)\n4. High-mercury fish (shark, swordfish)\n5. Excessive caffeine (limit to 1 cup)\n6. Alcohol (completely avoid)\n7. Processed meats (unless heated)\n8. Unwashed fruits/vegetables\n9. Excessive vitamin A (liver)\n10. Street food of questionable hygiene\n\nEat: fruits, vegetables, lean protein, whole grains, and take prenatal vitamins."},
    {"instruction": "How can I boost my metabolism?", "response": "Boosting metabolism naturally:\n1. Eat protein-rich foods — eggs, fish, beans\n2. Drink green tea\n3. Do strength training (muscle burns more calories)\n4. Drink cold water\n5. Get enough sleep\n6. Eat spicy foods (chili, pepper)\n7. Don't skip meals\n8. Drink coffee (in moderation)\n9. Stand up more (don't sit all day)\n10. Eat small frequent meals\nHigher metabolism = more calories burned = easier weight management. Exercise is the most effective metabolism booster."},
    {"instruction": "What are the symptoms of kidney disease?", "response": "Kidney disease symptoms:\n1. Changes in urination (more or less frequent)\n2. Foamy or dark urine\n3. Swelling in feet, ankles, hands, or face\n4. Persistent fatigue\n5. Shortness of breath\n6. Nausea and vomiting\n7. Loss of appetite\n8. Metallic taste in mouth\n9. Itchy skin\n10. High blood pressure\n\nRisk factors: diabetes, hypertension, family history, long-term painkiller use\nIf you have these symptoms, get a blood and urine test. Early detection prevents kidney failure."},
    {"instruction": "How can I take care of my teeth?", "response": "Dental care:\n1. Brush twice daily (morning and night)\n2. Use fluoride toothpaste\n3. Floss daily\n4. Avoid sugary drinks and snacks\n5. Visit dentist every 6 months\n6. Don't use teeth as tools (opening bottles)\n7. Limit coffee and tea (staining)\n8. Drink water after meals\n9. Replace toothbrush every 3 months\n10. Don't smoke (causes gum disease and oral cancer)\n11. Chew sugar-free gum after meals\nDental problems are expensive to fix — prevention is much cheaper. Brush properly: circular motions, 2 minutes."},
    {"instruction": "What is heat stroke and how do I prevent it?", "response": "Heat stroke (very dangerous in Nigerian heat):\nSymptoms: high body temperature (40°C+), confusion, hot dry skin, rapid pulse, headache, nausea, loss of consciousness\n\nPrevention:\n1. Drink plenty water (even when not thirsty)\n2. Avoid direct sun 11AM-3PM\n3. Wear light, loose clothing\n4. Use hat or umbrella\n5. Take breaks in shade\n6. Never leave children in cars\n\nIf heat stroke occurs:\n1. Move to cool area immediately\n2. Remove excess clothing\n3. Cool with water (not ice)\n4. Fan the person\n5. Seek medical help immediately\nHeat stroke can be fatal. Take Nigerian heat seriously."},
    {"instruction": "How can I manage my weight?", "response": "Weight management:\n1. Eat balanced meals — protein, vegetables, healthy carbs\n2. Portion control — use smaller plates\n3. Exercise regularly — 30 min daily\n4. Drink water before meals\n5. Limit processed and fried foods\n6. Reduce sugar intake\n7. Eat slowly — brain takes 20 min to feel full\n8. Get enough sleep\n9. Track what you eat\n10. Don't skip breakfast\n11. Limit eating after 8 PM\n12. Be consistent — it's a lifestyle, not a diet\nHealthy weight loss: 0.5-1 kg per week. Crash diets don't work long-term."},
    {"instruction": "What is the importance of vaccination?", "response": "Vaccination importance:\n1. Protects you from deadly diseases\n2. Protects others (herd immunity)\n3. Prevents outbreaks\n4. Saves money (treatment is expensive)\n5. Has saved millions of lives\n6. Safe and tested\n\nNigerian vaccination schedule includes: BCG, OPV, DPT, measles, yellow fever, hepatitis B, and others. Ensure children complete all vaccinations. Adults should get tetanus boosters and flu shots.\nVaccines are one of the greatest medical achievements. Don't believe misinformation — get vaccinated."},
    {"instruction": "How can I quit sugar addiction?", "response": "Quitting sugar:\n1. Gradual reduction — don't quit cold turkey\n2. Replace with fruits (natural sweetness)\n3. Read labels — sugar is hidden everywhere\n4. Avoid soda — drink water or zobo (no sugar)\n5. Cook at home (restaurant food has hidden sugar)\n6. Don't keep sweets at home\n7. Eat protein and fiber (keeps you full)\n8. Get enough sleep (cravings increase when tired)\n9. Manage stress (stress = sugar cravings)\n10. Allow occasional treats (don't be too strict)\nSugar addiction is real. It takes 2-3 weeks for cravings to decrease. Push through the first week."},

    # ========== FINANCE & MONEY (20) ==========
    {"instruction": "How do I open a Paystack account for my business?", "response": "To open Paystack:\n1. Go to paystack.com/signup\n2. Register with business email\n3. Fill business name and details\n4. Provide CAC number (if registered business)\n5. Add bank account for settlements\n6. Upload required documents (CAC, ID)\n7. Wait for approval (1-3 days for registered businesses)\n8. Get API keys (secret + public)\n9. Integrate on your website or use payment links\nFees: 1.5% local (cap N2,000), 3.9% international\nHARZ Paystack is LIVE — checkout links created for all 12 books at N3,200 each."},
    {"instruction": "What is compound interest and how does it work?", "response": "Compound interest is interest on your interest:\nSave N10,000/month at 10% annual return:\nYear 1: N126,000\nYear 5: N780,000\nYear 10: N2,000,000\nYear 20: N7,500,000\nYear 30: N22,000,000\nKey: Start early. Time is more powerful than the amount saved. Even N5,000/month compounds dramatically over decades. The earlier you start, the less you need to save overall."},
    {"instruction": "How can I save N100,000 in 6 months?", "response": "Saving N100,000 in 6 months (N16,667/month or N556/day):\n1. Set up automatic savings (auto-debit to savings account)\n2. Track every expense — cut unnecessary spending\n3. Reduce eating out — cook at home\n4. Use public transport instead of rides\n5. Cancel unused subscriptions\n6. Buy in bulk\n7. Sell things you don't need\n8. Side hustle — sell products, offer services\n9. Put savings where you can't easily access\n10. Stay disciplined — don't dip into savings\nUse PiggyVest, Cowrywise, or traditional ajo for automated savings."},
    {"instruction": "What is an emergency fund?", "response": "An emergency fund is savings for unexpected expenses:\n1. Target: 3-6 months of living expenses\n2. Keep in accessible but separate account\n3. Use ONLY for emergencies: job loss, illness, car repair\n4. Don't use for: vacations, gadgets, wants\n5. Start small — N50,000 first, build up\n6. Replenish after using\n7. Keep it liquid (not invested)\nAn emergency fund prevents debt when life happens. It's the foundation of financial security. Build it before investing."},
    {"instruction": "How do I track my expenses?", "response": "Tracking expenses:\n1. Write down every expense daily (notebook or app)\n2. Categorize: food, transport, bills, entertainment\n3. Use a simple Excel sheet\n4. Review weekly — spot patterns\n5. Budget for each category\n6. Track cash and digital payments\n7. Use apps: Spendee, Money Manager, or Excel\n8. Monthly summary: total spent vs budgeted\n9. Identify wasteful spending\n10. Adjust budget accordingly\nYou can't manage what you don't measure. Tracking is the first step to financial control."},
    {"instruction": "What are the best investment options in Nigeria?", "response": "Investment options in Nigeria:\n1. Treasury Bills — government-backed, safe, 10-15% return\n2. Mutual Funds — ARM, Stanbic, FBN (N5,000 minimum)\n3. Agriculture — farming (high returns, high risk)\n4. Real estate — land appreciates fast in Nigeria\n5. Stocks — Nigerian Stock Exchange (long-term)\n6. Crypto — Bitcoin, USDT (high risk, high reward)\n7. Business — invest in your own business (best ROI)\n8. Dollar savings — hedge against naira devaluation\nStart with: emergency fund → low-risk investments → higher risk as you grow. Never invest money you can't afford to lose."},
    {"instruction": "How do I create multiple income streams?", "response": "Creating multiple income streams:\n1. Primary: your main job or business\n2. Freelancing: Upwork, Fiverr (skills-based)\n3. Digital products: ebooks, courses (passive)\n4. Affiliate marketing: HARZ 10% commission\n5. Investments: treasury bills, mutual funds\n6. Rental income: rent out a room or property\n7. Content creation: YouTube, TikTok monetization\n8. Consulting: charge for your expertise\nDon't rely on one income source. Start with 2, build to 3-4. Each should require minimal ongoing time. Passive income is the goal."},
    {"instruction": "What is the 50/30/20 budgeting rule?", "response": "The 50/30/20 rule:\n50% — Needs: food, rent, transport, bills, essentials\n30% — Wants: entertainment, eating out, fashion, gadgets\n20% — Savings: emergency fund, investments, debt repayment\n\nExample with N100,000/month income:\nNeeds: N50,000\nWants: N30,000\nSavings: N20,000\n\nAdjust based on your situation. If income is low, increase needs % and reduce wants. As income grows, increase savings %. The key: always save something, even if small."},
    {"instruction": "How can I negotiate better prices?", "response": "Negotiating better prices:\n1. Do your research — know the market price\n2. Start lower than your target (leave room to go up)\n3. Be willing to walk away (your strongest tool)\n4. Buy in bulk for discounts\n5. Pay cash instead of transfer (some sellers prefer)\n6. Build relationship with sellers (regular customers get better deals)\n7. Compare prices from 3+ sellers\n8. Don't show too much interest (reduces your power)\n9. Ask 'is this your best price?'\n10. Time your purchase (end of month, holidays)\nIn Nigerian markets, negotiation is expected. Don't accept the first price — it's usually inflated."},
    {"instruction": "What is the difference between saving and investing?", "response": "Saving vs Investing:\n\nSaving:\n- Bank account, safe, liquid\n- Low return (2-5% per year)\n- For emergencies and short-term goals\n- Won't lose money\n- Inflation may eat the value\n\nInvesting:\n- Stocks, business, real estate, crypto\n- Higher return potential (10-50%+)\n- Higher risk (can lose money)\n- For long-term growth (3+ years)\n- Beats inflation over time\n\nBest approach: Save 3-6 months emergency fund first. Then invest the rest. Never invest your emergency fund."},
    {"instruction": "How do I avoid debt traps?", "response": "Avoiding debt traps:\n1. Don't borrow for consumption (clothes, phone, parties)\n2. Only borrow for investments that generate income\n3. Avoid loan apps with predatory rates (some charge 30%+ per month)\n4. Pay credit card balances in full each month\n5. Build emergency fund (prevents borrowing for emergencies)\n6. Live below your means\n7. Don't borrow to impress others\n8. If in debt, prioritize highest-interest debts first\n9. Negotiate with lenders if struggling\n10. Seek financial counseling if overwhelmed\nLoan apps in Nigeria can be dangerous — they access your contacts and shame you. Avoid them at all costs."},
    {"instruction": "What is financial freedom?", "response": "Financial freedom means your passive income covers your living expenses:\n1. You work because you want to, not because you have to\n2. Steps to freedom: earn more, spend less, save, invest, repeat\n3. Passive income sources: rental, dividends, digital products, business\n4. Track your 'freedom number': monthly expenses x 12 / expected return rate\n5. Example: N200,000/month expenses → N2.4M/year → at 10% return, need N24M invested\n6. Start small, be consistent, be patient\n7. Most people reach it in 10-20 years of disciplined saving and investing\nFinancial freedom is a marathon, not a sprint. Start today."},
    {"instruction": "How can I make money with my phone?", "response": "Making money with your phone in Nigeria:\n1. Sell products on WhatsApp/Instagram\n2. Freelance: write, design, manage social media\n3. Create content: TikTok, YouTube, Instagram\n4. Affiliate marketing: share HARZ links, earn 10%\n5. Online surveys (Swagbucks, though limited in Nigeria)\n6. Virtual assistant: manage emails, calendars\n7. Teach/tutor online\n8. Sell photos (Shutterstock)\n9. Play games (though earnings are small)\n10. App testing (UserTesting)\nYour phone is a business tool. The key is using it to create value, not just consume content."},
    {"instruction": "What is insurance and do I need it?", "response": "Insurance protects you from financial loss:\n1. Health insurance — covers medical bills\n2. Life insurance — supports family if you die\n3. Property insurance — covers damage to home/business\n4. Vehicle insurance — covers accidents (mandatory in Nigeria)\n5. Business insurance — covers business risks\n\nDo you need it? Yes, especially health and vehicle. Even basic insurance prevents one event from destroying your finances.\nIn Nigeria: NHIS for health (affordable), NAICOM for business. Start with health insurance — medical emergencies are the #1 cause of bankruptcy."},
    {"instruction": "How do I send money internationally from Nigeria?", "response": "Sending money internationally from Nigeria:\n1. Grey.co — virtual accounts, send/receive USD/GBP/EUR\n2. Payoneer — receive from platforms, send to bank\n3. Geegpay — virtual accounts, international transfers\n4. Crypto (USDT) — fastest, cheapest for large amounts\n5. WorldRemit — send to family abroad\n6. Sendcash — crypto-based international transfers\n7. Traditional banks — expensive, slow, limited\nFor receiving: Payoneer, Grey, Gumroad, Paddle. For sending: Crypto (USDT) is cheapest and fastest. Avoid traditional bank wire transfers — fees are high."},
    {"instruction": "What is a credit score and does it work in Nigeria?", "response": "Credit score in Nigeria:\n1. Measures your creditworthiness (how reliable you are at paying debts)\n2. Managed by Credit Bureaus: CRC, CreditRegistry, FirstCentral\n3. Built by: taking and repaying loans, paying bills on time\n4. Checked by: banks, lenders, some employers\n5. Good score = easier loan approval, lower interest rates\n6. Bad score = loan rejection, higher rates\n7. Check your score: CRC website or app\n\nTo build credit in Nigeria:\n- Pay loans on time\n- Pay utility bills regularly\n- Avoid multiple loan applications\n- Use credit cards responsibly (if available)"},
    {"instruction": "How do I do bookkeeping for my small business?", "response": "Simple bookkeeping for small business:\n1. Record every transaction (income and expense) daily\n2. Use a notebook or simple Excel sheet\n3. Columns: Date, Description, Income, Expense, Balance\n4. Keep all receipts\n5. Separate personal and business money\n6. Reconcile with bank statement monthly\n7. Calculate profit: Total Income - Total Expenses\n8. Review monthly: where is money coming from and going to?\n9. Save 20% of profit\n10. Use accounting apps as you grow: Wave (free), Zoho Books\nOur Excel Mastery book (N2,500) teaches how to build proper bookkeeping spreadsheets."},
    {"instruction": "What are treasury bills in Nigeria?", "response": "Treasury Bills (T-Bills) in Nigeria:\n1. Government-backed investment (very safe)\n2. Sold by CBN through banks\n3. Returns: 10-15% per year (better than savings)\n4. Minimum investment: N50,000 (varies by bank)\n5. Tenors: 91, 182, 364 days\n6. Interest paid upfront (you pay less than face value)\n7. Can be used as collateral for loans\n8. How to buy: Visit your bank, ask for T-bills form\n9. Good for: parking money safely while earning decent returns\n10. Risk: very low (government doesn't default)\nT-Bills are the safest investment in Nigeria for people who want guaranteed returns above inflation."},
    {"instruction": "How do I price my services competitively?", "response": "Pricing your services:\n1. Calculate your costs (time, materials, overhead)\n2. Research competitors' prices\n3. Add your desired profit margin\n4. Consider your experience level (beginners charge less)\n5. Value-based pricing: charge based on result for client\n6. Don't underprice (devalues your work)\n7. Don't overprice (lose clients)\n8. Offer packages (basic, standard, premium)\n9. Get 50% upfront payment\n10. Increase prices as you gain experience\nNigerian freelance rates: Writing N2,000-N10,000/article, Design N5,000-N50,000/project, Web dev N50,000-N500,000/project."},
    {"instruction": "What is the difference between revenue and profit?", "response": "Revenue vs Profit:\n\nRevenue (turnover): Total money from sales\nExample: You sell 100 books at N2,500 = N250,000 revenue\n\nProfit: What's left after costs\nCosts: N1,000/book (production) + N15,000 (marketing) = N115,000\nProfit = N250,000 - N115,000 = N135,000\n\nGross profit: Revenue - direct costs\nNet profit: Revenue - all costs (including taxes, rent, etc.)\n\nKey: Many businesses have high revenue but low or negative profit. Always track profit, not just revenue. Cash flow is even more important — profit on paper means nothing without cash."},

    # ========== MARKETING & SALES (20) ==========
    {"instruction": "Write a product launch announcement", "response": "🚀 BIG NEWS: HARZ Digital Learning — Complete 12-Book Bundle is LIVE!\n\n12 practical computer skills books covering everything from Excel to Python, cybersecurity to graphic design.\n\nBundle price: N6,000 (individual value N30,000 — you save 80%!)\n\nEach book includes:\n✅ 8-9 chapters\n✅ Hands-on exercises\n✅ Capstone projects\n✅ Step-by-step guidance\n\nPayment: UBA 2034326424 | Paystack | GDEG (10% off)\n\nGet instant access: https://hamzarabiu.gumroad.com\n\nDon't miss this! 🎉"},
    {"instruction": "Write a customer follow-up message", "response": "Hello [Name]! 😊\n\nThank you for your interest in HARZ Digital Learning books!\n\nDid you have a chance to look at the bundle deal? All 12 books for N6,000 (80% off!) — from Excel to Python, cybersecurity to graphic design.\n\nPayment options:\n1. UBA Transfer: 2034326424\n2. Paystack (card)\n3. GDEG token (10% discount!)\n\nBuy: https://hamzarabiu.gumroad.com\n\nAny questions? I'm here to help! 😊"},
    {"instruction": "Write a social media content calendar", "response": "HARZ Social Media Calendar (Weekly):\n\nMonday: Product spotlight (HarzDM Marketplace products)\nTuesday: Platform feature (Abuja Estate City)\nWednesday: Educational tip (EduWealth AI)\nThursday: Community spotlight (HARZ Connect)\nFriday: Bundle deal (50-80% off)\nSaturday: Music/Film platform feature\nSunday: Health & wellness (OMEGA Health AI)\n\nDaily: 2-3 posts across WhatsApp Status, Facebook, Instagram, Twitter\nWeekly: 1 long-form post (blog or thread)\nMonthly: 1 promotion or sale\n\nConsistency is key. Schedule posts in advance using free tools."},
    {"instruction": "How do I write a compelling headline?", "response": "Writing compelling headlines:\n1. Use numbers: '7 Ways to...' or '12 Books for...'\n2. Ask a question: 'Want to Earn More in 2026?'\n3. Create urgency: 'Limited Time: 80% Off!'\n4. Promise a benefit: 'Master Excel in 30 Days'\n5. Use power words: 'Complete', 'Proven', 'Secret', 'Ultimate'\n6. Keep it short (5-8 words ideal)\n7. Be specific, not vague\n8. Address the reader directly ('You')\n9. A/B test different headlines\n10. Match the content (don't clickbait)\n\nGood: '12 Books That Take You From Zero to Job-Ready'\nBad: 'Some Books About Computers'"},
    {"instruction": "Write a WhatsApp broadcast for Friday deal", "response": "🔥 FRIDAY DEAL: HARZ BUNDLE BLOWOUT! 🔥\n\nALL 12 HARZ Digital Learning books for just N6,000!\n\nWas N30,000 → Now N6,000\nThat's 80% OFF! 💰\n\nWhat's inside:\n✅ Excel Mastery\n✅ Python Programming\n✅ Web Development\n✅ Cybersecurity\n✅ Digital Marketing\n✅ Graphic Design\n✅ And 6 more!\n\nPay: UBA 2034326424 | Paystack | GDEG (10% off)\nBuy: https://hamzarabiu.gumroad.com\n\nOffer valid this weekend only! ⏰"},
    {"instruction": "How do I create a sales funnel for digital products?", "response": "Digital product sales funnel:\n1. Awareness — social media posts about the problem\n2. Interest — free content (tips, guides, mini-courses)\n3. Consideration — product page with benefits, reviews, price\n4. Decision — clear CTA with payment options\n5. Action — easy checkout (one-click, multiple payment methods)\n6. Delivery — instant download link\n7. Follow-up — thank you email, upsell bundle, ask for review\n8. Retention — broadcast list for future products\n\nHARZ funnel: WhatsApp post → free chapter → product page → Paystack/Gumroad → instant download → bundle upsell"},
    {"instruction": "Write a Google My Business description for HARZ", "response": "HARZ Digital Services is a Nigerian digital ecosystem providing 300+ digital products including computer skills books, ebooks, courses, and software. We offer 12 HARZ Digital Learning books covering Excel, Python, web development, cybersecurity, digital marketing, and more. Our 63+ platforms include HarzDM Marketplace, Abuja Estate City, HarzMusic, HarzFilm, EduWealth AI, and OMEGA Health AI. We accept bank transfer, Paystack, crypto, and Gumroad. Serving customers across Nigeria and globally. CAC RC: 321424, TIN: 24550860."},
    {"instruction": "Write a press release for HARZ", "response": "FOR IMMEDIATE RELEASE\n\nHARZ Digital Services Launches Complete AI-Powered Digital Ecosystem for Nigeria\n\nJalingo, Taraba State — HARZ Digital Services (CAC RC 321424) announces the launch of its 63+ platform digital ecosystem, featuring 300+ digital products, AI-powered customer support, and comprehensive digital learning resources for Nigerian entrepreneurs and students.\n\nThe HARZ Digital Learning Series, authored by founder Rabiu Hamza Mohammed, includes 12 practical computer skills books covering everything from Excel to Python programming, available for N2,500 each or N6,000 for the complete bundle.\n\nThe ecosystem also includes HarzDM Marketplace, Abuja Estate City, EduWealth AI, OMEGA Health AI, HarzMusic, HarzFilm, and HarzPay — all powered by 7 AI agents providing 24/7 customer support, marketing, and financial tracking.\n\nProducts are available at https://hamzarabiu.gumroad.com with instant delivery.\n\nContact: hamzarabiu390@gmail.com | 08028687857"},
    {"instruction": "Write a blog post title for HARZ", "response": "10 HARZ blog post titles:\n1. 'How I Built 63+ Digital Platforms with Zero Capital'\n2. '12 Books That Can Replace 4 Years of University'\n3. 'Why Nigerian Entrepreneurs Need Digital Skills in 2026'\n4. 'From Jalingo to the World: Building a Digital Ecosystem'\n5. 'How to Earn N500,000/Month with Digital Skills'\n6. 'The Complete Guide to Starting an Online Business in Nigeria'\n7. 'AI for Nigerian Businesses: What HARZ Learned'\n8. 'Why We Built Our Own AI Model Instead of Using ChatGPT'\n9. 'Digital Products vs Physical Products: Which Is Better?'\n10. 'How to Sell Digital Products on WhatsApp: HARZ Method'"},
    {"instruction": "Write a testimonial template", "response": "Customer testimonial template:\n\n'I bought the HARZ Digital Learning Bundle and it changed my career. Within 3 months of completing the Excel and Python books, I got a data analyst job paying N350,000/month. The books are practical, not just theory. Every chapter has exercises you actually do. Best N6,000 I ever spent.'\n— [Customer Name], [City]\n\nTips for collecting testimonials:\n1. Ask within 7 days of purchase (while excitement is high)\n2. Ask specific questions: What changed? What did you learn?\n3. Get permission to use their name and city\n4. Include numbers if possible (salary increase, time saved)"},
    {"instruction": "Write an Instagram caption for HARZ books", "response": "📚 Want to level up your career in 2026?\n\nThe HARZ Digital Learning Series covers everything:\n✅ Excel to advanced level\n✅ Python programming\n✅ Web development\n✅ Cybersecurity\n✅ Digital marketing\n✅ And more!\n\n12 books. One bundle. N6,000 only (was N30,000!)\n\nThat's 80% OFF! 🔥\n\nPay: UBA 2034326424 | Paystack | GDEG\nBuy: link in bio 👆\n\n#HARZDigital #DigitalLearning #NigeriaJobs #Skills2026 #LearnToEarn"},
    {"instruction": "Write a cold DM template for potential customers", "response": "Hi [Name]! 👋\n\nI noticed you're interested in digital skills. I wanted to share something that might help:\n\nHARZ Digital Learning — 12 practical computer skills books covering Excel, Python, web dev, cybersecurity, marketing, and more.\n\nBundle: N6,000 (was N30,000 — 80% off!)\n\nNot pushy — just wanted to share in case it's useful. If you have questions, I'm happy to help.\n\nLink: https://hamzarabiu.gumroad.com\nPay: UBA 2034326424 | Paystack | GDEG (10% off)\n\nNo pressure at all! 😊"},
    {"instruction": "How do I write a value proposition?", "response": "Writing a value proposition:\n\nFormula: I help [target] achieve [result] by [method].\n\nHARZ example: 'We help Nigerian entrepreneurs and job seekers master digital skills through 12 practical computer skills books, covering everything from Excel to Python, at an affordable price of N6,000.'\n\nKey elements:\n1. Target audience — who you serve\n2. Result — what they achieve\n3. Method — how you deliver\n4. Differentiator — why you, not competitors\n5. Proof — numbers, testimonials\n\nKeep it to 1-2 sentences. Put it on your website, bio, and marketing materials."},
    {"instruction": "Write an SMS marketing message", "response": "HARZ: Get 12 digital skills books (Excel, Python, Web Dev + more) for N6,000 only (was N30,000). 80% OFF! Pay UBA 2034326424 or buy at hamzarabiu.gumroad.com. Instant download. Reply STOP to opt out."},
    {"instruction": "Write a partnership proposal email", "response": "Subject: Partnership Opportunity with HARZ Digital Services\n\nDear [Name],\n\nI'm Rabiu Hamza Mohammed, founder of HARZ Digital Services (CAC RC 321424), a Nigerian digital ecosystem with 63+ platforms and 300+ digital products.\n\nI'd like to propose a partnership between HARZ and [Company Name]. We see alignment in:\n- Shared target audience (Nigerian entrepreneurs)\n- Complementary products/services\n- Mutual growth opportunity\n\nWhat we offer:\n- Access to our 63+ platform ecosystem\n- Affiliate commission (10% on sales)\n- Co-branded digital products\n- Joint marketing campaigns\n\nI'd love to discuss this further. Are you available for a call this week?\n\nBest regards,\nRabiu Hamza Mohammed\nHARZ Digital Services\nhamzarabiu390@gmail.com | 08028687857"},
    {"instruction": "Write a refund policy for HARZ", "response": "HARZ Refund Policy:\n\n1. Digital products are non-refundable once downloaded, except:\n - File is corrupted (we'll send replacement)\n - Product doesn't match description\n - Double payment\n2. Refund request must be made within 7 days of purchase\n3. Provide order reference and reason for refund\n4. Approved refunds processed within 5 business days\n5. Refund method: same as payment method\n6. We reserve the right to decline refunds for:\n - Change of mind\n - Failure to read product description\n - Unauthorized sharing of product\n\nFor refund requests: contact us via WhatsApp 08028687857 or hamzarabiu390@gmail.com with your order number."},
    {"instruction": "Write a thank you page for after purchase", "response": "🎉 Thank You for Your Purchase!\n\nYour HARZ Digital Learning product is ready!\n\nDownload link: [LINK]\n\nYour order reference: [ORDER_ID]\n\nWhat to do next:\n1. Download your file immediately\n2. Save it to your device\n3. Start learning today!\n4. Join our WhatsApp community for support\n\nQuestions? WhatsApp: 08028687857\nEmail: hamzarabiu390@gmail.com\n\nWant ALL 12 books? Upgrade to the bundle (N6,000) and save 80%!\n\nThank you for choosing HARZ Digital Services! 🙏"},
    {"instruction": "Write a competition/giveaway announcement", "response": "🎁 HARZ GIVEAWAY! 🎁\n\nWin the COMPLETE HARZ Digital Learning Bundle (12 books, N30,000 value) for FREE!\n\nTo enter:\n1. Follow HARZ Digital Services\n2. Like this post\n3. Tag 3 friends who need digital skills\n4. Share this post to your status\n\nWinner announced [date]. Good luck! 🍀\n\n#HARZGiveaway #DigitalSkills #Nigeria"},
    {"instruction": "How do I write a case study for HARZ?", "response": "HARZ Case Study Template:\n\nTitle: How [Customer Name] Used HARZ Books to [Achieve Result]\n\nChallenge: [Customer] was struggling with [problem]. They couldn't [do what they wanted].\n\nSolution: They bought the HARZ [specific book/bundle] for N[price]. They studied [X] chapters and completed [project].\n\nResult: Within [timeframe], [Customer] achieved [specific result]. They now [current status].\n\nQuote: '[Customer testimonial about the experience]'\n\nROI: Invested N[amount], earned N[amount] = [X]% ROI.\n\nCase studies are powerful because they show real results. Collect them from satisfied customers."},

    # ========== PERSONAL DEVELOPMENT (20) ==========
    {"instruction": "How can I build self-confidence?", "response": "Building self-confidence:\n1. Start with small wins — set and achieve small goals daily\n2. Stop comparing yourself to others — compare to your past self\n3. Learn new skills — competence builds confidence\n4. Dress well — looking good helps feeling good\n5. Stand tall — posture affects confidence\n6. Speak up — express your opinions\n7. Accept compliments graciously\n8. Embrace failure as learning, not defeat\n9. Surround yourself with supportive people\n10. Practice — confidence comes from doing things repeatedly\n11. Prepare thoroughly for challenges\n12. Exercise regularly\nConfidence is a muscle — the more you use it, the stronger it gets."},
    {"instruction": "How do I overcome procrastination?", "response": "Overcoming procrastination:\n1. Use the 2-minute rule — if it takes less than 2 minutes, do it now\n2. Break big tasks into small steps\n3. Use Pomodoro: 25 min work, 5 min break\n4. Remove distractions (phone, social media)\n5. Set deadlines (even for personal tasks)\n6. Start with the hardest task first (eat the frog)\n7. Reward yourself after completing tasks\n8. Find your 'why' — connect tasks to goals\n9. Forgive yourself for past procrastination\n10. Track your progress — visual progress motivates\n11. Have an accountability partner\n12. Create a routine — habits beat motivation\nProcrastination is an emotion problem, not a time problem. Address the fear or overwhelm underneath."},
    {"instruction": "How can I be more productive?", "response": "Productivity tips:\n1. Plan your day the night before\n2. Prioritize: do important tasks first, not urgent ones\n3. Single-task — multitasking is a myth\n4. Take breaks — 50 min work, 10 min break\n5. Batch similar tasks together\n6. Delegate what others can do\n7. Say no to non-essential requests\n8. Use the 80/20 rule — 20% effort = 80% results\n9. Turn off notifications while working\n10. Set a timer for tasks (creates urgency)\n11. Review and adjust weekly\n12. Get enough sleep — tired brain is unproductive\nProductivity is not about doing more — it's about doing what matters."},
    {"instruction": "How do I set SMART goals?", "response": "SMART goal framework:\n\nS — Specific: 'Earn N500,000 from digital products' (not 'make more money')\nM — Measurable: 'Sell 100 books at N5,000 each' (track progress)\nA — Achievable: 'Sell 100 books in 3 months' (realistic based on effort)\nR — Relevant: 'This helps me reach financial freedom' (connected to bigger goal)\nT — Time-bound: 'By December 31, 2026' (deadline)\n\nExample: 'I will sell 100 HARZ book bundles at N6,000 each by December 31, 2026, earning N600,000 through WhatsApp marketing and affiliate sales.'\n\nWrite it down. Review weekly. Adjust monthly. Celebrate when achieved."},
    {"instruction": "How can I improve my communication skills?", "response": "Improving communication:\n1. Listen more than you speak (80/20 rule)\n2. Think before you speak\n3. Be clear and concise — avoid unnecessary words\n4. Use simple language (don't show off with big words)\n5. Maintain eye contact\n6. Pay attention to body language\n7. Ask questions to understand, not to respond\n8. Show empathy — acknowledge others' feelings\n9. Practice public speaking (start small)\n10. Record yourself and review\n11. Read regularly (builds vocabulary)\n12. Join a debate or toastmasters club\nGood communication is the #1 skill for career and business success. Everyone can improve with practice."},
    {"instruction": "How do I handle failure?", "response": "Handling failure:\n1. Accept it — failure is normal, not shameful\n2. Feel the emotions — but don't wallow\n3. Analyze what went wrong (honestly)\n4. What did you learn? (every failure teaches something)\n5. What would you do differently?\n6. Separate the failure from your identity — you are not the failure\n7. Talk to someone — don't isolate\n8. Remember: the most successful people failed the most\n9. Start again — but smarter\n10. 'I have not failed. I've just found 10,000 ways that won't work.' — Edison\nFailure is data. It tells you what doesn't work so you can find what does. The only real failure is giving up."},
    {"instruction": "How can I develop a growth mindset?", "response": "Developing a growth mindset:\n1. Believe abilities can be developed (not fixed)\n2. Embrace challenges (not avoid them)\n3. See effort as the path to mastery\n4. Learn from criticism (not ignore it)\n5. Be inspired by others' success (not threatened)\n6. Replace 'I can't' with 'I can't YET'\n7. Focus on the process, not just the result\n8. Celebrate effort, not just achievement\n9. View mistakes as learning opportunities\n10. Read books about growth and learning\nFixed mindset: 'I'm not good at math.'\nGrowth mindset: 'I'm not good at math YET, but I can learn.'\nThe brain is like a muscle — it grows with exercise."},
    {"instruction": "How do I build good habits?", "response": "Building good habits:\n1. Start tiny — one push-up, one page, one minute\n2. Attach to existing habits ('After I pray, I will read one page')\n3. Make it easy (reduce friction)\n4. Track visually (calendar, app, notebook)\n5. Don't break the chain (miss one day max)\n6. Reward yourself for consistency\n7. Be patient — habits take 21-66 days to form\n8. Environment matters — remove triggers for bad habits\n9. Replace bad habits, don't just eliminate them\n10. Get an accountability partner\n\nTo break a bad habit:\n1. Identify the trigger\n2. Replace with a good habit\n3. Remove the cue\n4. Make the bad habit harder to do\nHabits are the compound interest of self-improvement."},
    {"instruction": "How can I manage my time better?", "response": "Time management:\n1. Track your time for 1 week (see where it goes)\n2. Identify time wasters (social media, TV)\n3. Schedule everything (calendar, not memory)\n4. Time-block: assign specific time for each task\n5. Prioritize: Important + Urgent > Important > Urgent > Neither\n6. Learn to say no\n7. Delegate when possible\n8. Batch similar tasks\n9. Set time limits (Parkinson's Law: work expands to fill time)\n10. Take breaks (prevents burnout)\n11. Review daily and weekly\n12. Protect your mornings — most productive time\nTime is your most valuable non-renewable resource. Spend it wisely."},
    {"instruction": "How do I deal with negative people?", "response": "Dealing with negative people:\n1. Limit time spent with them\n2. Don't engage in their negativity\n3. Change the subject to positive topics\n4. Set boundaries — what you will and won't accept\n5. Don't take their negativity personally (it's about them, not you)\n6. Be the positive influence (lead by example)\n7. Surround yourself with positive people instead\n8. Practice empathy — they may be going through difficulties\n9. Protect your energy — walk away when needed\n10. Don't try to change them — only change yourself\nYour environment shapes you. The people around you either lift you up or pull you down. Choose wisely."},
    {"instruction": "How can I stay motivated?", "response": "Staying motivated:\n1. Connect to your 'why' — the deeper reason behind your goals\n2. Set small, achievable goals (celebrate wins)\n3. Track progress (visual progress motivates)\n4. Surround yourself with motivated people\n5. Read inspiring stories and quotes\n6. Take care of your health (energy = motivation)\n7. Reward yourself for milestones\n8. Visualize success\n9. Remember past successes\n10. Take action even when you don't feel like it (action creates motivation, not the other way around)\n11. Remove obstacles and distractions\n12. Get enough sleep and exercise\nMotivation is not something you wait for — it's something you create through action."},
    {"instruction": "How do I find my passion?", "response": "Finding your passion:\n1. What do you enjoy doing for hours without noticing time?\n2. What topics do you naturally research or read about?\n3. What problems do you enjoy solving?\n4. What would you do even if not paid?\n5. What did you love as a child?\n6. Try many things — passion is discovered through action\n7. Ask friends what they see you light up about\n8. Combine your skills and interests\n9. Don't wait for a 'calling' — build passion through mastery\n10. Passion often follows competence, not the other way around\nThe best way to find your passion is to get good at something. Mastery creates passion."},
    {"instruction": "How can I become more disciplined?", "response": "Building discipline:\n1. Start with one habit at a time\n2. Set clear rules (no ambiguity)\n3. Create a routine (same time, same place)\n4. Remove temptations from your environment\n5. Use accountability (tell someone your goal)\n6. Track your streaks (don't break the chain)\n7. Forgive lapses (get back on track immediately)\n8. Focus on identity ('I am a disciplined person')\n9. Make the right choice the easy choice\n10. Practice delayed gratification\n11. Understand your 'why' (discipline requires reason)\n12. Start small (1% better each day)\nDiscipline = freedom. It's not about restriction — it's about choosing what you want most over what you want now."},
    {"instruction": "How do I overcome fear?", "response": "Overcoming fear:\n1. Name the fear (vague fears are scarier than specific ones)\n2. Ask: what's the worst that could happen? (usually not as bad as you think)\n3. Ask: what's the best that could happen? (usually amazing)\n4. Take small steps toward the fear (exposure)\n5. Prepare thoroughly (knowledge reduces fear)\n6. Accept that fear is normal (everyone feels it)\n7. Act despite fear — courage is not absence of fear\n8. Visualize success\n9. Talk to someone who's done what you fear\n10. Remember: fear of regret is worse than fear of failure\n'Feel the fear and do it anyway.' Most fears never come true. The ones that do are usually manageable."},
    {"instruction": "How can I improve my decision-making?", "response": "Better decision-making:\n1. Gather information (but don't over-research)\n2. Consider alternatives (at least 3 options)\n3. Weigh pros and cons\n4. Think about long-term consequences\n5. Use the 10-10-10 rule: how will I feel in 10 minutes, 10 months, 10 years?\n6. Avoid decisions when emotional or tired\n7. Trust your gut for small decisions (save energy)\n8. Use logic for big decisions (don't just trust gut)\n9. Set a deadline (don't decide forever)\n10. Accept that perfect decisions don't exist — good enough is fine\n11. Review past decisions to learn\n12. Don't regret — make the best decision with available info, then move forward"},
    {"instruction": "How can I be happier?", "response": "Keys to happiness:\n1. Gratitude — write 3 good things daily\n2. Relationships — quality connections matter most\n3. Health — exercise, sleep, eat well\n4. Purpose — have something meaningful to do\n5. Give to others — helping makes you happier\n6. Live in the present — not past regrets or future anxieties\n7. Compare down, not up (be grateful for what you have)\n8. Limit social media (comparison steals joy)\n9. Spend money on experiences, not things\n10. Accept what you can't control\n11. Forgive (holding grudges hurts you)\n12. Simplify your life — less stuff, less stress\nHappiness is not having what you want — it's wanting what you have."},
    {"instruction": "How do I build resilience?", "response": "Building resilience:\n1. Reframe challenges as opportunities\n2. Focus on what you can control\n3. Build a support network\n4. Practice self-care (physical and mental)\n5. Develop problem-solving skills\n6. Set realistic expectations\n7. Learn from setbacks\n8. Maintain perspective (this too shall pass)\n9. Find meaning in difficult times\n10. Take action (don't feel helpless)\n11. Practice optimism (realistic optimism)\n12. Keep going — persistence beats talent\nResilience is like a muscle — it grows stronger with each challenge you overcome. The strongest people are not those who never fall, but those who keep getting up."},
    {"instruction": "How can I stop overthinking?", "response": "Stopping overthinking:\n1. Set a time limit for decisions\n2. Write it down (externalizing helps)\n3. Distinguish between productive thinking and rumination\n4. Ask: 'Will this matter in 5 years?'\n5. Take action (action kills overthinking)\n6. Practice mindfulness (be present)\n7. Distract yourself with productive activities\n8. Talk to someone (get outside perspective)\n9. Accept imperfection (good enough is good)\n10. Limit information intake (too much info = analysis paralysis)\n11. Set 'worry time' (15 min/day, then stop)\n12. Exercise (burns nervous energy)\nOverthinking is your brain trying to protect you, but it backfires. Action is the antidote."},
    {"instruction": "How can I be more assertive?", "response": "Being more assertive:\n1. Express your needs clearly and directly\n2. Use 'I' statements ('I feel' not 'You always')\n3. Say no without guilt\n4. Maintain eye contact\n5. Speak clearly and at a steady pace\n6. Stand your ground (but listen to others)\n7. Set and enforce boundaries\n8. Don't apologize for having needs\n9. Practice in small situations first\n10. Respect others' assertiveness too\nAssertiveness is not aggression — it's the middle ground between being passive (too quiet) and aggressive (too forceful). You deserve to be heard."},
    {"instruction": "How do I find a mentor?", "response": "Finding a mentor:\n1. Identify what you want to learn\n2. Look for someone who's where you want to be\n3. Start by following their content (books, videos, posts)\n4. Engage with their work (comment, share)\n5. Ask a specific question (not 'be my mentor')\n6. Offer value first (how can you help them?)\n7. Be respectful of their time\n8. Follow up with results ('I tried what you suggested and...')\n9. Formalize the relationship when trust is built\n10. You can have multiple mentors for different areas\nA mentor doesn't have to be in person — books, podcasts, and courses are mentoring too. HARZ books are like having Rabiu as your mentor for digital skills."},

    # ========== PRODUCT-SPECIFIC (15) ==========
    {"instruction": "What is in the Computer Fundamentals book?", "response": "Computer Fundamentals & Windows Productivity (Book 1) covers:\n1. Hardware components — CPU, RAM, storage, GPU\n2. Windows interface — desktop, taskbar, start menu\n3. Professional file management — folders, naming, backup\n4. Software troubleshooting — common fixes\n5. Networking basics — WiFi, sharing, printers\n6. System optimization — speed up your PC\n7. Backup & recovery — protect your data\n8. Multitasking — work efficiently\n9. Virtual desktops — organize your workspace\nCapstone: Build a complete efficient daily workstation setup.\nPrice: N2,500. Perfect for beginners."},
    {"instruction": "What is in the Touch Typing book?", "response": "Touch Typing & Keyboard Efficiency (Book 6):\n1. Home row foundations — proper finger placement\n2. Full alphabet mastery\n3. Numbers and symbols\n4. Speed drills — gradually increase speed\n5. Error correction techniques\n6. Ergonomics — prevent strain and injury\n7. 30-day structured practice plan\n8 chapters with hands-on exercises.\nFor students, office workers, freelancers, programmers — everyone who types daily.\nPrice: N2,500.\nTyping fast saves hours every week. It's the most underrated skill."},
    {"instruction": "What is in the Internet & Email book?", "response": "Internet, Email & Online Productivity (Book 5):\n1. Power browsing — tabs, bookmarks, shortcuts\n2. Search operators — find anything on Google\n3. Professional email habits\n4. Inbox organization — folders, labels, filters\n5. Cloud storage — Google Drive, Dropbox\n6. Online collaboration — Google Workspace\n7. Password management — secure your accounts\n8. Phishing protection — avoid scams\n9 chapters for digital professionals.\nPrice: N2,500.\nEssential for anyone working online — from office staff to freelancers."},
    {"instruction": "What is in the Digital Marketing book?", "response": "Digital Marketing (Book 10):\n1. Marketing funnel — awareness to purchase\n2. Audience profiling — know your customer\n3. Content marketing — create valuable content\n4. Social media strategy — platform-by-platform\n5. SEO basics — rank on Google\n6. Paid advertising — Meta Ads, Google Ads\n7. Email marketing — build and nurture lists\n8. Analytics — measure ROI\nCapstone: Complete 90-day marketing plan.\nPrice: N2,500.\nFor business owners, freelancers, and marketing beginners."},
    {"instruction": "What is in the Web Development book?", "response": "Web Development Fundamentals (Book 8):\n1. HTML structure — tags, elements, semantic HTML\n2. CSS styling — colors, fonts, spacing\n3. Flexbox & Grid — modern layouts\n4. Responsive design — mobile-friendly sites\n5. JavaScript fundamentals — variables, functions, DOM\n6. DOM manipulation — interactive elements\n7. Forms & validation — collect user input\nCapstone: Build a complete responsive landing page.\nPrice: N2,500. Beginner to intermediate level.\nPerfect for anyone who wants to build websites."},
    {"instruction": "Tell me about the Entrepreneur Mindset Ebook", "response": "The Entrepreneur Mindset Ebook:\n- 160 pages on developing entrepreneurial thinking\n- Covers: fear management, decision-making, resilience, opportunity recognition, execution discipline\n- 20 interviews with Nigerian entrepreneurs\n- 30-day mindset transformation challenge\n- Written for Nigerian context\n- Price: N3,000\n- Buy: https://hamzarabiu.gumroad.com\n\nFor aspiring entrepreneurs who need the mental foundation before starting a business."},
    {"instruction": "Tell me about the Content Creator Ebook", "response": "The Content Creator Ebook 2026:\n- 180 pages for content creators\n- Covers: content strategy, multi-platform publishing, AI tools, monetization (ads, sponsorships, products, courses), audience growth, analytics\n- 30 creator case studies from YouTube, TikTok, Instagram\n- Price: N3,500\n- Buy: https://hamzarabiu.gumroad.com\n\nFor anyone who wants to make money creating content in Nigeria."},
    {"instruction": "Tell me about the Freelancer Ebook", "response": "The Complete Freelancer Ebook 2026:\n- 180 pages on building a freelancing career from Nigeria\n- Covers: skill selection, portfolio building, client acquisition (Upwork, Fiverr, LinkedIn)\n- Pricing strategies, contract templates, tax guide\n- 30 success stories from Nigerian freelancers\n- Price: N3,500\n- Buy: https://hamzarabiu.gumroad.com\n\nFor anyone who wants to earn in USD from Nigeria through freelancing."},
    {"instruction": "Tell me about the Agriculture Ebook", "response": "Agriculture Business Ebook Nigeria:\n- 230-page guide to profitable agriculture\n- Covers: crop farming, livestock, fish farming, snail farming, poultry, processing\n- Each section: ROI calculations, market analysis, government loan info\n- PDF with financial templates\n- Price: N4,500\n- Buy: https://hamzarabiu.gumroad.com\n\nFor aspiring and current farmers who want to make agriculture profitable."},
    {"instruction": "What is the 2048 game?", "response": "2048 Game HTML5 Customizable Edition:\n- HTML5 puzzle game\n- 5 board sizes (3x3 to 7x7)\n- 10 themes\n- Undo function\n- High scores tracking\n- Smooth animations\n- Mobile-responsive with swipe controls\n- Full source code included\n- Price: N2,000\n- Buy: https://hamzarabiu.gumroad.com\n\nPerfect for game portals, educational sites, and ad monetization."},
    {"instruction": "What is the WhatsApp Wealth ebook?", "response": "WhatsApp Wealth Ebook:\n- 100 pages on building wealth through WhatsApp Business\n- Covers: catalog setup, status marketing, broadcast lists, auto-replies, payment integration, group monetization\n- 30 templates included\n- Written specifically for Nigerian entrepreneurs\n- Price: N2,500\n- Buy: https://hamzarabiu.gumroad.com\n\nWhatsApp is the #1 business tool in Nigeria — this ebook shows you how to monetize it."},
    {"instruction": "Can I see the table of contents for the Excel book?", "response": "Microsoft Excel Mastery (Book 2) Table of Contents:\nCh1: Review of Excel Basics\nCh2: Dynamic Formulas (VLOOKUP, XLOOKUP, INDEX-MATCH)\nCh3: PivotTables and PivotCharts\nCh4: Professional Dashboards\nCh5: Data Validation and Conditional Formatting\nCh6: Power Query for Data Cleaning\nCh7: VBA Macros — Automation\nCh8: Charts and Data Visualization\nCh9: Capstone — Build a Business Dashboard\nPrice: N2,500. For office staff, analysts, business owners."},
    {"instruction": "What is in the PowerPoint book?", "response": "PowerPoint & Outlook Mastery (Book 4):\n1. Slide Master — professional templates\n2. Visual design rules — colors, fonts, layouts\n3. Data visualization — charts that tell stories\n4. Animations and transitions\n5. Presenter View — present like a pro\n6. Outlook inbox system — organize emails\n7. Calendar management — schedule effectively\n8. Rules, templates, email automation\nCapstone: Build a complete client pitch deck and send it professionally.\nPrice: N2,500. For consultants, managers, sales teams, business owners."},
    {"instruction": "What is in the Word book?", "response": "Microsoft Word Professional Mastery (Book 3):\n1. Styles — consistent formatting throughout\n2. Long documents — table of contents, sections\n3. Tables — create and format professional tables\n4. Mail Merge — send personalized letters to 100+ people\n5. Track Changes — collaborate and review\n6. Templates — save time with reusable designs\n7. Advanced layouts — newsletters, brochures\nCapstone: Create a professional business proposal.\nPrice: N2,500. For admin staff, consultants, students, business owners."},
    {"instruction": "What is in the Data Analysis book?", "response": "Data Analysis & Excel Analytics (Book 12):\n1. Statistical thinking — mean, median, standard deviation\n2. Descriptive statistics\n3. Data cleaning at scale\n4. Exploratory analysis with PivotTables\n5. Correlation & trend analysis\n6. Forecasting techniques\n7. Power Pivot & DAX\n8. Storytelling with data\nCapstone: End-to-end business analysis from raw data to recommendation.\nPrice: N2,500. For aspiring data analysts and decision-makers."},

    # ========== GENERAL KNOWLEDGE (20) ==========
    {"instruction": "What is the internet?", "response": "The internet is a global network of connected computers:\n1. Started in the 1960s as a military project (ARPANET)\n2. Now connects billions of devices worldwide\n3. Runs on protocols: TCP/IP, HTTP, DNS\n4. Key services: web (websites), email, file transfer, streaming\n5. No single owner — decentralized network\n6. ISPs (Internet Service Providers) provide access\n7. In Nigeria: MTN, Airtel, Glo, 9Mobile provide internet access\n8. Bandwidth and speed vary by location and provider\nThe internet has transformed how we communicate, learn, work, and do business. HARZ operates entirely on the internet — all 63+ platforms are web-based."},
    {"instruction": "What is 5G?", "response": "5G is the fifth generation of mobile internet:\n1. 100x faster than 4G\n2. Lower latency (almost instant response)\n3. Can connect more devices simultaneously\n4. Enables: self-driving cars, remote surgery, IoT, VR/AR\n5. Available in parts of Nigeria (MTN, Airtel)\n6. Requires 5G-compatible phone\n7. More expensive than 4G currently\n8. Will gradually expand across Nigeria\nFor most HARZ users, 4G is sufficient. Our platforms are optimized to work even on 3G connections."},
    {"instruction": "What is the metaverse?", "response": "The metaverse is a concept of a virtual world:\n1. Digital spaces where people interact as avatars\n2. Virtual and augmented reality combined\n3. Virtual real estate, events, shopping, work\n4. Companies like Meta (Facebook) investing billions\n5. Still in early stages — not mainstream yet\n6. Challenges: hardware, adoption, privacy\n7. Could transform: education, work, entertainment, commerce\nFor now, focus on practical digital skills. The metaverse may become relevant in 5-10 years."},
    {"instruction": "What is IoT (Internet of Things)?", "response": "IoT is everyday objects connected to the internet:\n1. Smart home — lights, thermostat, security cameras\n2. Wearables — fitness trackers, smartwatches\n3. Industrial — sensors in factories\n4. Agriculture — soil sensors, irrigation\n5. Smart cities — traffic, waste, energy management\n6. Examples: Alexa, smart TV, fitness band\nHARZ has an IoT entity system — IoTDevice, IoTAlert, IoTAutomation for tracking and managing smart devices in the ecosystem."},
    {"instruction": "What is big data?", "response": "Big data refers to extremely large datasets:\n1. Volume — massive amounts of data\n2. Velocity — data generated at high speed\n3. Variety — data in many formats (text, video, sensor)\n4. Veracity — data quality and accuracy\n5. Sources: social media, sensors, transactions, websites\n6. Analyzed with: Python, SQL, Hadoop, Spark\n7. Used for: predictions, recommendations, optimization\n8. Examples: Netflix recommendations, Google search, Amazon suggestions\nHARZ collects data from 63+ platforms — customer interactions, orders, CRM, analytics — forming our own big data ecosystem."},
    {"instruction": "What is the gig economy?", "response": "The gig economy is work based on short-term contracts:\n1. Freelancing — Upwork, Fiverr\n2. Ride-sharing — Uber, Bolt\n3. Delivery — food delivery apps\n4. Micro-tasks — data labeling, surveys\n5. Content creation — YouTube, TikTok\n6. Pros: flexibility, multiple income streams, be your own boss\n7. Cons: no benefits, unstable income, no job security\n8. Growing rapidly in Nigeria — especially freelancing and content creation\nHARZ supports the gig economy — our books teach skills for freelancing, and our platforms enable selling digital products independently."},
    {"instruction": "What is digital literacy?", "response": "Digital literacy is the ability to use technology effectively:\n1. Basic: using a computer, smartphone, internet\n2. Communication: email, messaging, video calls\n3. Information: searching, evaluating, using online information\n4. Creation: making documents, presentations, content\n5. Safety: protecting yourself online\n6. Problem-solving: using tech to solve problems\n7. Advanced: programming, data analysis, digital marketing\nDigital literacy is no longer optional — it's essential for every job and business. HARZ Digital Learning books are designed to build digital literacy from zero to professional."},
    {"instruction": "What is a startup?", "response": "A startup is a young company designed to grow fast:\n1. Usually tech-based or innovative\n2. Seeks to solve a problem in a new way\n3. Often funded by investors (angels, VCs)\n4. High risk, high potential reward\n5. Examples: Flutterwave, Paystack, Jumia (Nigerian startups)\n6. Key difference from small business: startups aim to scale rapidly\n7. Stages: idea → seed → series A/B/C → IPO or acquisition\n8. Most startups fail — but those that succeed can be huge\nHARZ is like a startup — started from zero, built 63+ platforms, aiming for massive scale across Nigeria and Africa."},
    {"instruction": "What is e-commerce?", "response": "E-commerce is buying and selling online:\n1. Types: B2C (business to consumer), B2B (business to business), C2C (consumer to consumer)\n2. Platforms: Jumia, Konga, Amazon, Shopify\n3. Digital products: ebooks, courses, software (highest margins)\n4. Physical products: require inventory, shipping\n5. Payment: Paystack, bank transfer, cards, crypto\n6. Key metrics: conversion rate, average order value, customer acquisition cost\n7. In Nigeria: WhatsApp is the #1 e-commerce platform\nHARZ does e-commerce through Gumroad, Getly, and HarzDM Marketplace — all digital products, instant delivery."},
    {"instruction": "What is cloud computing in simple terms?", "response": "Cloud computing in simple terms:\nImagine instead of buying your own computer, you rent one over the internet. That's cloud computing.\n\nInstead of:\n- Buying servers → Rent from AWS, Render\n- Storing files on hard drive → Store on Google Drive\n- Installing software → Use web apps\n\nBenefits: cheaper, scale easily, access from anywhere, no maintenance.\n\nHARZ is 100% cloud: GitHub Pages (websites), Render (backend), Base44 (database). We own zero physical servers. Total cost: N0/month."},
    {"instruction": "What is a SWOT analysis?", "response": "SWOT analysis helps you understand your business:\n\nS — Strengths (internal, positive): What you do well. HARZ: 63+ platforms, 300+ products, AI agents, zero infrastructure cost.\n\nW — Weaknesses (internal, negative): What to improve. HARZ: limited marketing budget, relies on one person, hardware constraints.\n\nO — Opportunities (external, positive): Market trends. HARZ: growing digital economy in Nigeria, increasing internet penetration, youth population.\n\nT — Threats (external, negative): Risks. HARZ: competition from bigger platforms, regulatory changes, economic instability.\n\nUse SWOT to make strategic decisions. Review quarterly."},
    {"instruction": "What is a competitive advantage?", "response": "Competitive advantage is what makes customers choose you over others:\n\nTypes:\n1. Price — cheapest option\n2. Quality — better product\n3. Service — better customer experience\n4. Speed — faster delivery\n5. Niche — serving a specific market others ignore\n6. Brand — reputation and recognition\n7. Network effects — more users = more value (like social media)\n8. Technology — better tools or methods\n\nHARZ competitive advantages:\n- Nigerian-focused (local context, Hausa/Pidgin support)\n- 63+ integrated platforms (one account, everything)\n- AI-powered (7 agents, 24/7 support)\n- Zero infrastructure cost (sustainable low pricing)\n- Affordable (N2,500-N6,000 products)"},
    {"instruction": "What is a business model?", "response": "A business model is how you make money:\n\nCommon models:\n1. Direct sales — sell products (HARZ books)\n2. Subscription — recurring monthly payment\n3. Marketplace — connect buyers and sellers, take commission\n4. Advertising — free content, earn from ads\n5. Affiliate — earn commission promoting others\n6. Freemium — basic free, premium paid\n7. Licensing — sell rights to use your IP\n8. Services — charge for time/expertise\n\nHARZ uses multiple models:\n- Direct sales (books, ebooks)\n- Marketplace (HarzDM, Getly)\n- Affiliate (10% commission)\n- Services (consultations)\n- Freemium (free AI chat, paid products)"},
    {"instruction": "What is a KPI?", "response": "KPI (Key Performance Indicator) measures how well your business is doing:\n\nCommon KPIs:\n1. Revenue — total money earned\n2. Profit margin — profit as % of revenue\n3. Customer acquisition cost — how much to get one customer\n4. Conversion rate — % of visitors who buy\n5. Average order value — average purchase amount\n6. Customer lifetime value — total a customer spends over time\n7. Churn rate — % of customers who stop buying\n8. ROI — return on investment\n\nHARZ KPIs to track:\n- Books sold per month\n- Revenue (NGN + USD)\n- CRM inquiries and conversion\n- Platform uptime\n- Product upload completion"},
    {"instruction": "What is the sharing economy?", "response": "The sharing economy is people sharing resources for money:\n1. Uber/Bolt — share your car\n2. Airbnb — share your home\n3. TaskRabbit — share your skills/time\n4. Food delivery — share your kitchen or bike\n5. Tool rental — share equipment\n\nPros: extra income, utilize idle resources, flexible\nCons: regulatory issues, no benefits, unstable\n\nIn Nigeria: Bolt and Uber are big. Airbnb is growing. Skill-sharing (freelancing) is the biggest opportunity.\nHARZ enables the sharing economy — sell your knowledge through digital products, share your skills through freelancing."},
    {"instruction": "What is nanotechnology?", "response": "Nanotechnology is engineering at the atomic level:\n1. Working with materials 1-100 nanometers in size\n2. A nanometer is 1 billionth of a meter\n3. Applications: medicine (targeted drug delivery), electronics (smaller chips), materials (stronger, lighter), energy (better batteries)\n4. Future: could revolutionize manufacturing, health, computing\n5. Still mostly in research and early commercial stages\n6. Not directly relevant to most Nigerian businesses yet, but worth knowing about\n\nThe future of technology will be shaped by nanotechnology, AI, and quantum computing."},
    {"instruction": "What is quantum computing?", "response": "Quantum computing uses quantum mechanics for computation:\n1. Regular computers use bits (0 or 1). Quantum uses qubits (both 0 and 1 simultaneously)\n2. Exponentially faster for certain problems\n3. Could solve: drug discovery, climate modeling, cryptography\n4. Not ready for commercial use yet (still experimental)\n5. Companies: Google, IBM, Microsoft investing billions\n6. Could break current encryption (security concern)\n7. 10-20 years from widespread use\nFor now, regular computing is more than enough for any business. But quantum will transform everything when it arrives."},
    {"instruction": "What is the difference between WiFi and data?", "response": "WiFi vs Mobile Data:\n\nWiFi:\n- Connects to a router (fixed location)\n- Usually faster and more stable\n- Often cheaper (or free at cafes/offices)\n- Limited range\n- Good for: home, office, downloading large files\n\nMobile Data:\n- Connects to cell towers (anywhere with coverage)\n- 3G, 4G, 5G speeds\n- More expensive per GB\n- Works everywhere with network coverage\n- Good for: on-the-go, traveling, areas without WiFi\n\nTips for Nigeria: Use WiFi at home/office for downloads. Switch to data when out. Buy night plans for large downloads (cheaper)."},
    {"instruction": "What is a VPN and should I use one?", "response": "A VPN (Virtual Private Network) encrypts your internet:\n1. Hides your IP address (your location)\n2. Encrypts your data (hackers can't read it)\n3. Bypasses geo-restrictions (access content from other countries)\n4. Protects you on public WiFi\n5. Free VPNs: ProtonVPN, Windscribe (limited data)\n6. Paid VPNs: ExpressVPN, NordVPN (better speed and security)\n\nShould you use one in Nigeria?\n- If you use public WiFi: YES\n- If you want to access international content: YES\n- If you're concerned about privacy: YES\n- For general browsing at home: optional\n\nDon't use free VPNs for banking — they may not be secure enough."},
    {"instruction": "What is a cryptocurrency wallet?", "response": "A crypto wallet stores your digital currencies:\n\nTypes:\n1. Hot wallet — connected to internet (phone apps): Trust Wallet, MetaMask, Phantom\n2. Cold wallet — offline (USB-like device): Ledger, Trezor (most secure)\n3. Exchange wallet — on a crypto exchange: Binance\n\nHow it works:\n1. Wallet has a public address (like account number) — share to receive\n2. Wallet has a private key (like password) — NEVER share\n3. Seed phrase (12-24 words) — backup to restore if phone lost\n\nImportant: If you lose your seed phrase, you lose your crypto forever. Write it on paper, not on your phone.\n\nHARZ uses Polygon wallets for GDEG tokens and TRC20 wallets for USDT."},
    {"instruction": "What is the difference between a blog and a website?", "response": "Blog vs Website:\n\nBlog:\n- Regularly updated content (articles/posts)\n- Chronological (newest first)\n- Written content focused\n- Personal or business voice\n- Examples: WordPress blog, Medium, Blogger\n\nWebsite:\n- Static or semi-static pages\n- Organized by sections (Home, About, Services, Contact)\n- Can include a blog as one section\n- More structured\n- Examples: Business website, portfolio, e-commerce store\n\nA blog IS a type of website. But not all websites are blogs.\n\nHARZ: Our platform sites are websites. We could add a blog for SEO and content marketing."},
    {"instruction": "What is content marketing?", "response": "Content marketing is creating valuable content to attract customers:\n1. Instead of selling directly, you provide value first\n2. Types: blog posts, videos, podcasts, social media, ebooks\n3. Build trust and authority in your niche\n4. Customers come to you (inbound) instead of you chasing them (outbound)\n5. Long-term strategy (takes 6-12 months to see results)\n6. Very cost-effective (content is free to create)\n7. SEO + content = free traffic for years\n\nHARZ content marketing examples:\n- Free tips on WhatsApp Status\n- Educational posts on social media\n- Our books themselves are content products\n- This AI assistant providing free information\nGive value first, sell second. That's content marketing."},

    # ========== CONVERSATIONAL PATTERNS (15) ==========
    {"instruction": "I don't understand", "response": "No problem! Let me explain it more simply. Which part is confusing? I'm happy to break it down step by step. There are no dumb questions — I'm here to help you understand."},
    {"instruction": "Ba na fahimta", "response": "Babu matsala! Bari in fada a sauqi. Wanne sashe ba ka fahimta ba? Na shirya don fashin shi mataki mataki. Babu wani mummunan tambaya — na nan don taimaka maka ka fahimci."},
    {"instruction": "Can you help me?", "response": "Of course! That's what I'm here for. 😊 What do you need help with? I can assist with products, payments, business advice, tech questions, health info, and more. Just tell me what's on your mind."},
    {"instruction": "Za ka iya taimaka min?", "response": "Tabbata! Saboda haka nike nan. 😊 Me kake buƙatar taimako akan? Zan iya taimaka da products, biyan kuɗi, shawara akan kasuwanci, fasaha, lafiya, da sauransu. Ka fadi min abin da ke kan zuciyar ka."},
    {"instruction": "That's expensive", "response": "I understand! Here's the thing — each book is N2,500 and gives you skills worth much more. But if you want maximum value, the bundle is N6,000 for ALL 12 books (was N30,000). That's N500 per book! Also, using GDEG token gives you 10% off. Think of it as an investment — N2,500 can help you earn N500,000+. That's 20,000% ROI."},
    {"instruction": "What if I don't like the product?", "response": "We want you to be satisfied! If the product doesn't match the description or the file is corrupted, we'll replace it or refund you. Just contact us within 7 days with your order number. We stand behind our products because they're practical and valuable — but we understand if it's not for you."},
    {"instruction": "Are you a robot?", "response": "I'm HARZ AI — an AI assistant, not a human, but also not just a simple robot. I'm a fine-tuned model trained specifically on HARZ Digital Services data. I can understand English, Hausa, and Pidgin, answer questions, give advice, and help with business. I'm designed to be helpful like a knowledgeable friend. 😊"},
    {"instruction": "Shin kai robot ne?", "response": "Ni HARZ AI ne — AI assistant ne, ba mutum ba ne, amma kuma ba robot ɗin yadda kuke tsammani ba. An horar da ni musamman akan bayanan HARZ Digital Services. Na iya Hausa, Turanci, da Pidgin, amsa tambayoyi, bada shawara, da taimaka akan kasuwanci. An tsara ni in zama kamar aboki mai ilimi. 😊"},
    {"instruction": "Tell me a joke", "response": "Here's one: Why did the Python developer go broke? Because he used up all his cache! 😄\n\nOkay, here's a better one: A programmer's wife says 'Go to the store and buy a loaf of bread. If they have eggs, get a dozen.' The programmer comes back with 12 loaves of bread. Wife: 'Why did you buy 12 loaves?!' Programmer: 'They had eggs!' 😂"},
    {"instruction": "Ka fadi min barkwanci", "response": "Ga wata: Malami ya tambayi ɗalibi 'Me zai faru idan ka rasa aikin nan gaba?' Dalibi ya ce 'Zan zama malami!' 😄\n\nKo kuma: Wani mutum ya saya kwamfyuta. Ya tambayi mai sayarwa 'Wanne madogarar da ta fi kyau?' Mai sayarwa ya ce 'Wadda ba ka rasa ba!' 😂"},
    {"instruction": "What's your favorite book?", "response": "My favorite is the Complete 12-Book Bundle — because it covers everything! From computer basics to Python programming, cybersecurity to graphic design. It's like having a complete digital education in your pocket. And at N6,000 for 12 books, it's the best deal in HARZ! 📚"},
    {"instruction": "Do you sleep?", "response": "I don't sleep! 😊 I'm available 24/7, 365 days a year. Whether it's 2 AM or 2 PM, I'm always here to help. That's one advantage of being an AI — no sleep needed. So if you have a question at midnight, just ask!"},
    {"instruction": "How fast can you respond?", "response": "I respond in seconds! Unlike human customer service that takes hours or days, I'm instant. Send a message and I'll answer right away. I can handle multiple conversations at once too — no waiting in line. That's the power of AI. 😊"},
    {"instruction": "What languages do you speak?", "response": "I speak three languages:\n1. English — for international and formal communication\n2. Hausa — for Northern Nigeria and Hausa speakers\n3. Pidgin — for casual Nigerian communication\n\nI was trained on all three. So whether you prefer 'Hello', 'Sannu', or 'How far?', I understand you! 😊"},
    {"instruction": "Me harsuna da kake magana?", "response": "Ina magana da yaruka uku:\n1. Turanci — don saduwar duniya da na yau da kullum\n2. Hausa — don arewacin Najeriya da masu magana da Hausa\n3. Pidgin — don tattaunawa ta yau da kullun a Najeriya\n\nAn horar da ni akan duka ukun. Don haka ko 'Hello', ko 'Sannu', ko 'How far?', na gane ka! 😊"},
]

# Combine all
all_data = v3 + new_examples

# Deduplicate
seen = set()
unique = []
for item in reversed(all_data):
    key = item["instruction"].lower().strip()
    if key not in seen:
        seen.add(key)
        unique.append(item)
unique.reverse()

with open("harz_training_data_v4.jsonl", "w") as f:
    for item in unique:
        f.write(json.dumps(item) + "\n")

print(f"v3 data: {len(v3)}")
print(f"New examples: {len(new_examples)}")
print(f"After dedup: {len(unique)}")
print("Saved to harz_training_data_v4.jsonl")
