#!/usr/bin/env python3
"""
HARZ AI — Fine-Tuning Dataset v3.0 (EXPANDED)
300+ examples — comprehensive knowledge for HARZ AI
"""

import json

# Load v2 data first
v2_data = []
with open("harz_training_data_v2.jsonl") as f:
    for line in f:
        v2_data.append(json.loads(line))

# New examples to add (v3 expansion)
new_examples = [
    # ========== NIGERIAN BUSINESS DEEP DIVE (20) ==========
    {"instruction": "How do I start selling on Instagram in Nigeria?", "response": "Selling on Instagram in Nigeria:\n1. Create an Instagram business account (free)\n2. Switch to professional account for analytics\n3. Take clear photos of your products\n4. Write compelling captions with prices\n5. Use relevant hashtags (#naijabusiness #nigeria #buynaija)\n6. Post consistently (1-2 times daily)\n7. Use Instagram Stories for behind-the-scenes\n8. Respond to DMs quickly\n9. Accept payment via bank transfer or Paystack\n10. Use Instagram Shopping tags\n11. Run ads (N1,000-N5,000/day to start)\n12. Collaborate with micro-influencers\nConsistency is key — most successful sellers post daily for 6+ months before seeing real results."},
    {"instruction": "How can I use Facebook for business in Nigeria?", "response": "Facebook for business in Nigeria:\n1. Create a Facebook Business Page (free)\n2. Fill in all business info (address, hours, contact)\n3. Post products with photos and prices\n4. Join Nigerian buy/sell groups\n5. Create a Facebook Shop\n6. Run Facebook ads (start N1,000/day)\n7. Use Facebook Marketplace for local sales\n8. Go Live to showcase products\n9. Respond to comments and messages fast\n10. Share customer reviews and testimonials\nFacebook has the largest user base in Nigeria — over 30M users. It's essential for any business."},
    {"instruction": "What are the best businesses to start in Nigeria with N50,000?", "response": "Businesses to start with N50,000 in Nigeria:\n1. Digital products (ebooks, templates) — buy from HARZ, resell\n2. Mini-importation (phone accessories from AliExpress)\n3. Food delivery (cook and deliver to offices)\n4. Social media management for businesses\n5. Phone repair (learn on YouTube, buy tools N15,000)\n6. Snack making (puff-puff, chin chin, plantain chips)\n7. Graphic design (Canva free + WhatsApp orders)\n8. Copywriting (start on Fiverr)\n9. WhatsApp business (resell products)\n10. Tutorial center (primary/secondary students)\nKey: Start with what you know, keep costs low, reinvest profits."},
    {"instruction": "How do I register a domain name in Nigeria?", "response": "Registering a domain name:\n1. Choose a name (short, memorable, relevant)\n2. Check availability on Namecheap, GoDaddy, or ResellerClub\n3. .com costs N5,000-N10,000/year\n4. .ng costs N5,000-N15,000/year\n5. .com.ng costs N2,500-N5,000/year\n6. Register through your chosen registrar\n7. Set up DNS (point to your hosting)\n8. Enable auto-renewal to avoid losing it\nHARZ can help you register domains through our hosting service. Contact us for bulk domain registration and discounts."},
    {"instruction": "How can I accept international payments from Nigeria?", "response": "Accepting international payments from Nigeria:\n1. Payoneer — receive from Upwork, Fiverr, Amazon\n2. Grey.co — virtual USD/GBP/EUR accounts\n3. Geegpay — virtual foreign accounts\n4. Gumroad — sell digital products globally\n5. Paddle — Merchant of Record for global sales\n6. Stripe — through Payoneer or registered entity abroad\n7. Crypto (USDT, BTC) — borderless, fast\n8. PayPal — limited but works for receiving from some platforms\nRecommendation: Use Gumroad or Paddle for digital products, Payoneer for freelancing, crypto for direct transfers."},
    {"instruction": "What is dropshipping and can I do it in Nigeria?", "response": "Dropshipping is selling products without holding inventory:\n1. You list products on your store/social media\n2. Customer pays you\n3. You order from supplier (cheaper price)\n4. Supplier ships directly to customer\n5. You keep the profit difference\nIn Nigeria:\n- Suppliers: AliExpress, 1688, local wholesalers\n- Platforms: WhatsApp, Instagram, Jumia\n- Payment: Customer pays you first, you pay supplier\n- Challenge: delivery time (7-21 days from China)\n- Tip: Start with phone cases, accessories (light, cheap, fast selling)\n- Risk: quality control — order samples first"},
    {"instruction": "How do I write a sales page that converts?", "response": "Writing a high-converting sales page:\n1. Headline — state the big benefit (not the feature)\n2. Subheadline — expand on the promise\nn3. Problem — show you understand their pain\n4. Solution — present your product as the answer\n5. Benefits — bullet points of what they gain\n6. Social proof — testimonials, reviews, numbers\n7. Offer — price + bonuses + guarantee\n8. Urgency — limited time, limited quantity\n9. CTA — clear 'Buy Now' button\n10. FAQ — address common objections\nExample: 'Master Excel in 30 Days — From Zero to Job-Ready. N2,500 only. 500+ students trained. 90% got jobs within 3 months. Buy now!'"},
    {"instruction": "What is a sales funnel?", "response": "A sales funnel is the path customers take from awareness to purchase:\n1. Awareness — they discover you (social media, ads, search)\n2. Interest — they engage (like, comment, visit profile)\n3. Consideration — they evaluate (read reviews, compare)\n4. Decision — they buy\n5. Retention — they come back or refer others\nFor HARZ:\n- Awareness: Facebook/WhatsApp posts about books\n- Interest: Free chapter download\n- Consideration: Product page with reviews\n- Decision: Pay N2,500 via Paystack/transfer\n- Retention: Bundle offer (N6,000 for all 12)\nBuild funnels for each product. Start simple: post → link → payment → delivery."},
    {"instruction": "How can I build trust with online customers?", "response": "Building trust with online customers in Nigeria:\n1. Show your face — people buy from people, not logos\n2. Share your CAC registration (we have RC 321424)\n3. Post customer reviews and screenshots\n4. Offer money-back guarantee\n5. Respond to messages within minutes\n6. Deliver on promises — fast delivery, quality products\n7. Use business phone number and email\n8. Share behind-the-scenes content\n9. Be transparent about prices\n10. Admit mistakes and fix them fast\n11. Use verified payment methods (Paystack, bank transfer)\nTrust takes months to build and seconds to destroy. Always over-deliver."},
    {"instruction": "How do I handle customer complaints?", "response": "Handling customer complaints:\n1. Listen fully — don't interrupt\n2. Apologize sincerely — even if not your fault\n3. Acknowledge their frustration\n4. Ask questions to understand the issue\n5. Offer a solution immediately\n6. Follow up after resolution\n7. Learn from the complaint\n8. Never argue or get defensive\n9. Document complaints to spot patterns\n10. Escalate serious issues to management\nExample: 'I'm sorry your download link didn't work. Let me send you a fresh link right now. Here it is: [link]. Is it working now? Thank you for your patience!'"},
    {"instruction": "What is the best time to post on social media in Nigeria?", "response": "Best posting times in Nigeria (WAT):\n1. Facebook: 8-10 AM, 12-2 PM, 7-9 PM\n2. Instagram: 11 AM-1 PM, 7-9 PM\n3. Twitter/X: 8-10 AM, 12-2 PM, 6-8 PM\n4. WhatsApp: 7-9 AM, 12-2 PM, 8-10 PM\n5. TikTok: 11 AM-3 PM, 7-11 PM\n6. LinkedIn: 8-10 AM, 12-1 PM (weekdays)\nKey: Post when people are on breaks, commuting, or relaxing. Test different times and track engagement. Weekends work well for lifestyle and entertainment content."},
    {"instruction": "How do I create a brand identity?", "response": "Creating a brand identity:\n1. Brand name — memorable, easy to pronounce\n2. Logo — simple, works in black and white\n3. Colors — 2-3 main colors (HARZ uses green and gold)\n4. Fonts — 1-2 fonts consistently\n5. Voice — how you talk (HARZ is warm, direct, professional)\n6. Tagline — short phrase (HARZ: 'Digital Solutions for Nigeria')\n7. Values — what you stand for\n8. Visual style — consistent across all platforms\n9. Business cards and letterhead\n10. Social media templates\nKeep it consistent everywhere — website, WhatsApp, Instagram, Facebook. Consistency builds recognition."},
    {"instruction": "What is a cooperative society and how does it work?", "response": "A cooperative society is a group that pools money for mutual benefit:\n1. Members contribute regularly (daily, weekly, monthly)\n2. Pooled money is given to members in rotation or as loans\n3. Types: Ajo/Esusu (informal), Registered Cooperative (formal)\n4. Benefits: access to loans, savings, group buying power\n5. To register: Ministry of Commerce, 10+ members, constitution\n6. Common in Nigeria: thrift, credit, agricultural, housing\n7. Each member has equal voting rights\n8. Profits shared based on contribution\nHARZ has an Ajo platform — AjoGroup entity for tracking contributions, payouts, and member management."},
    {"instruction": "How can I use Twitter for business in Nigeria?", "response": "Twitter/X for business in Nigeria:\n1. Optimize your bio — what you do + link\n2. Tweet value — tips, insights, not just sales\n3. Use Nigerian trending hashtags\n4. Engage in conversations (reply to big accounts)\n5. Share threads (educational content)\n6. Post 3-5 times daily\n7. Use images and videos (more engagement)\n8. Participate in Twitter chats\n9. Run Twitter ads (start N1,000/day)\n10. Build relationships, not just followers\nNigerian Twitter is active — tech, business, entertainment communities. Engage genuinely, don't just broadcast."},
    {"instruction": "How do I create a WhatsApp Business catalog?", "response": "WhatsApp Business catalog setup:\n1. Download WhatsApp Business app (free)\n2. Go to Settings > Business Tools > Catalog\n3. Add products with: name, price, description, photo, link\n4. Organize by categories\n5. Share catalog link with customers\n6. Customers browse and order from catalog\n7. You receive order notifications\n8. Set up auto-reply for common questions\n9. Use labels to organize customers (new, pending, paid)\n10. Use broadcast lists for promotions\nWhatsApp catalog is like a mini-store. It's the most powerful sales tool in Nigeria."},
    {"instruction": "What is the difference between LLC and sole proprietorship in Nigeria?", "response": "Business types in Nigeria:\n1. Sole Proprietorship — one owner, easy to register, no separation between personal and business assets, CAC registration N10,000-N15,000\n2. LLC (Limited Liability Company) — owners' personal assets protected, separate legal entity, CAC registration N25,000-N50,000, need annual returns\n3. Partnership — 2+ owners, shared liability\n4. NGO/Non-profit — for charitable purposes\nHARZ is registered as HI Water/Block Industry (CRBN 321424) — a business name registration, not LLC. For most small businesses, sole proprietorship or business name registration is sufficient."},
    {"instruction": "How do I calculate profit margin?", "response": "Profit margin calculation:\nFormula: (Selling Price - Cost Price) / Selling Price x 100\n\nExample: You buy an ebook for N2,500 and sell it for N5,000\nProfit margin = (5,000 - 2,500) / 5,000 x 100 = 50%\n\nTypes:\n1. Gross margin — after cost of goods\n2. Net margin — after all expenses (tax, rent, etc.)\n3. Operating margin — after operating costs\n\nTarget: Digital products should have 70-90% margin (no inventory). Physical products: 20-40% is normal.\n\nHARZ books: Cost is time to write. Selling at N2,500 with near-100% margin."},
    {"instruction": "What is NIN and why do I need it?", "response": "NIN (National Identification Number) is your unique ID as a Nigerian citizen:\n1. Issued by NIMC (National Identity Management Commission)\n2. Required for: bank accounts, BVN, passport, driver's license, SIM registration, tax\n3. How to get: visit NIMC enrollment center with birth certificate and proof of address\n4. It's free to register\n5. You get a National ID card\n6. NIN is 11 digits\n7. Link your NIN to your phone numbers (mandatory)\n8. Can be used for digital identity verification\nHARZ Identity platform uses NIN for KYC verification in our financial services."},
    {"instruction": "How can I protect my business idea in Nigeria?", "response": "Protecting your business idea in Nigeria:\n1. Trademark — protect your name and logo (register at IPO Nigeria, N20,000-N50,000)\n2. Copyright — protects creative works (books, music, software), automatic but register for evidence\n3. Patent — protects inventions (expensive, complex)\n4. NDAs — have people sign Non-Disclosure Agreements\n5. Don't share full details publicly until protected\n6. Register your domain name\n7. Keep records of when you created things\nReality: Ideas are cheap, execution is everything. Don't worry too much about someone stealing your idea — focus on executing better than anyone else."},
    {"instruction": "What are the tax obligations for a small business in Nigeria?", "response": "Small business taxes in Nigeria:\n1. TIN (Tax Identification Number) — free, required for all businesses\n2. Company Income Tax (CIT) — 30% of profits (companies only, not sole proprietors)\n3. VAT (Value Added Tax) — 7.5% on sales, if turnover > N25M/year\n4. Personal Income Tax — on your salary/profits, paid to state\n5. Withholding Tax — on certain payments (rent, professional fees)\n6. Small businesses (< N25M turnover) — exempt from VAT and most taxes\n7. File annual returns\n8. Keep good records\nFor most HARZ-sized businesses: register TIN, keep records, pay minimal tax. Consult a tax professional as you grow."},

    # ========== ADVANCED MARKETING (15) ==========
    {"instruction": "Write a WhatsApp status marketing sequence", "response": "WhatsApp Status Marketing Sequence (5 days):\n\nDay 1: Problem awareness\n'Did you know 80% of Nigerians lack basic computer skills? Don't be one of them. 📚'\n\nDay 2: Solution introduction\n'HARZ Digital Learning — 12 books that take you from zero to job-ready. N2,500 each. 🔥'\n\nDay 3: Social proof\n'500+ students trained. 90% got jobs within 3 months. Here's what Ahmed said: \"This book changed my career!\" 💪'\n\nDay 4: Offer\n'BUNDLE DEAL: All 12 books for N6,000 (was N30,000). 80% OFF! Limited time. 🚀'\n\nDay 5: CTA\n'Don't miss out! Pay to UBA 2034326424 or buy on Gumroad. Link below! 👇'\n\nPost 1-2 statuses daily. Use images. Keep text short."},
    {"instruction": "Write a Telegram channel announcement", "response": "🚀 *HARZ DIGITAL LEARNING — COMPLETE BUNDLE*\n\n📚 12 practical computer skills books\n💰 Regular price: N30,000\n🔥 Bundle price: N6,000 (80% OFF!)\n\n*What you get:*\n✅ Computer Fundamentals\n✅ Excel Mastery\n✅ Word & PowerPoint\n✅ Python Programming\n✅ Web Development\n✅ Cybersecurity\n✅ Digital Marketing\n✅ Graphic Design with Canva\n✅ Data Analysis\n\n*Payment:*\nUBA Transfer: 2034326424\nPaystack | GDEG (10% off) | USDT\n\n🛒 Buy: https://hamzarabiu.gumroad.com\n\n*Instant download after payment!*"},
    {"instruction": "Write an email marketing template", "response": "Subject: 80% OFF — Master Digital Skills with HARZ\n\nHello [Name],\n\nWant to level up your career in 2026?\n\nThe complete HARZ Digital Learning Series is now available at 80% off.\n\n12 books covering:\n- Excel & Word mastery\n- Python programming\n- Web development\n- Cybersecurity\n- Digital marketing\n- Graphic design\n- Data analysis\n\nBundle price: N6,000 (was N30,000)\n\nPay via UBA transfer (2034326424), Paystack, or GDEG token (10% extra discount).\n\nBuy now: https://hamzarabiu.gumroad.com\n\nDon't miss this offer — it won't last forever.\n\nBest regards,\nHARZ Digital Services"},
    {"instruction": "Write a Facebook ad copy for HARZ books", "response": "🎯 LEARN DIGITAL SKILLS — GET HIRED IN 2026!\n\nStop scrolling if you want a better job. 👀\n\nThe HARZ Digital Learning Series gives you 12 practical computer skills books:\n\n✅ Excel to advanced level\n✅ Python programming\n✅ Web development\n✅ Digital marketing\n✅ Cybersecurity\n✅ And more!\n\nFrom beginner to job-ready in weeks, not years.\n\nBundle price: N6,000 (was N30,000 — save 80%!)\n\n👉 Buy now: https://hamzarabiu.gumroad.com\nPay with card, transfer, or crypto.\n\n#DigitalSkills #NigeriaJobs #LearnToEarn"},
    {"instruction": "Write a product description for the Excel book", "response": "📊 Microsoft Excel Mastery — Intermediate to Advanced\n\nTired of struggling with spreadsheets? This book takes you from basic formulas to advanced automation.\n\n*What you'll learn:*\n- Dynamic formulas (VLOOKUP, XLOOKUP, INDEX-MATCH)\n- PivotTables for data analysis\n- Professional dashboards\n- VBA macros for automation\n- Power Query for data cleaning\n\n*9 chapters* with hands-on exercises.\n*Perfect for:* Office staff, analysts, business owners, job seekers.\n*Price:* N2,500 | Buy: https://hamzarabiu.gumroad.com\n\nMaster Excel = master your career."},
    {"instruction": "Write a product description for the Python book", "response": "🐍 Python Programming — From Fundamentals to Real-World Automation\n\nLearn the most in-demand programming language in 2026.\n\n*What you'll learn:*\n- Variables, control flow, data structures\n- Functions and OOP\n- File handling and automation\n- pandas for data analysis\n- requests for web APIs\n- Real-world projects\n\n*Capstone project:* Build a command-line Sales Report Generator\n\n*9 chapters* — beginner to practical fluency.\n*Price:* N2,500 | Buy: https://hamzarabiu.gumroad.com\n\nPython = job-ready in months, not years."},
    {"instruction": "Write a Pidgin marketing post for agriculture ebook", "response": "🌾 You wan start farming business for Naija? 🚜\n\nThis 230-page ebook cover everything:\n✅ Crop farming\n✅ Livestock\n✅ Fish farming\n✅ Snail farming\n✅ Poultry\n✅ ROI calculations\n✅ Government loan info\n\nPrice: N4,500 only!\n\nPay: UBA 2034326424, card, or crypto\nBuy: https://hamzarabiu.gumroad.com\n\nNo dull yourself — start your farm business today! 🚀"},
    {"instruction": "Write a Hausa ad for the cybersecurity book", "response": "🔒 Tsaro na Intanet — Kare kanka da kasuwancinka!\n\nLittafin Cybersecurity Essentials na koya maka:\n✅ Yadda za ka gane phishing da scams\n✅ Password security da MFA\n✅ Kare wayarka da kwamfyutarka\n✅ Data backup strategy\n✅ Safe browsing\n\nN2,500 kawai!\nPay: UBA 2034326424\nBuy: https://hamzarabiu.gumroad.com\n\nKada a bar scamers su ci ka! 🛡️"},
    {"instruction": "How do I write good product descriptions?", "response": "Writing product descriptions that sell:\n1. Start with the benefit, not the feature\n2. Use the customer's language\n3. Be specific (not 'high quality' but '230 pages, 9 chapters')\n4. Include numbers and facts\n5. Address objections (price, time, difficulty)\n6. Add social proof (students trained, results)\n7. Use formatting (bold, bullets, emojis sparingly)\n8. End with clear CTA (buy link, price, payment method)\n9. Keep it scannable — people skim\n10. Write for one person, not a crowd\nBad: 'A great book about Excel.'\nGood: 'Master Excel in 9 chapters — from VLOOKUP to VBA macros. N2,500. 500+ students trained.'"},
    {"instruction": "Write a retargeting message for abandoned cart", "response": "👋 Hi [Name]! You were checking out the HARZ Digital Learning Bundle but didn't complete your purchase.\n\nHere's a reminder: N6,000 for ALL 12 books (80% off!) 💰\n\nThe offer is still available. Pay now:\nUBA: 2034326424\nOr buy here: https://hamzarabiu.gumroad.com\n\nQuestions? Just reply to this message 😊"},
    {"instruction": "Write a seasonal promo for New Year", "response": "🎉 NEW YEAR, NEW SKILLS! 🎊\n\nStart 2026 right — master digital skills with HARZ!\n\n🔥 NEW YEAR SPECIAL: All 12 books for N5,000 (was N6,000!)\n\nThat's N30,000 worth of knowledge for just N5,000.\n\n✅ Excel ✅ Python ✅ Web Dev ✅ Marketing ✅ Design ✅ And more!\n\nPay: UBA 2034326424 | Paystack | GDEG (10% off)\nBuy: https://hamzarabiu.gumroad.com\n\nMake this year count! 🚀"},
    {"instruction": "Write a customer testimonial request", "response": "Hello [Name]! 😊\n\nThank you for buying from HARZ Digital Services! We hope you're enjoying your product.\n\nCould you take 30 seconds to share your experience? Your review helps other Nigerians discover our products.\n\nJust reply with:\n1. What you bought\n2. What you liked most\n3. Would you recommend it? (Yes/No)\n\nThank you for supporting HARZ! 🙏"},
    {"instruction": "Write a bundle upsell message", "response": "💡 Wait — you can get ALL 12 books for less!\n\nYou're buying one book for N2,500. But the complete bundle is N6,000 — that's 12 books for the price of 3!\n\nYou save N24,000!\n\nBooks included: Excel, Word, PowerPoint, Python, Web Dev, Cybersecurity, Marketing, Design, Data Analysis, and more.\n\nUpgrade to the bundle: https://hamzarabiu.gumroad.com\nPay: UBA 2034326424 | Paystack | GDEG\n\nDon't miss 80% savings! 🚀"},
    {"instruction": "Write a holiday sale announcement", "response": "🎄 HARZ HOLIDAY SALE — 80% OFF! 🎅\n\nGive the gift of knowledge this holiday season!\n\nALL 12 HARZ Digital Learning books: N6,000 (was N30,000!)\n\nPerfect gift for students, job seekers, and entrepreneurs.\n\nPay: UBA 2034326424 | Paystack | GDEG (10% off)\nBuy: https://hamzarabiu.gumroad.com\n\nKnowledge is the best gift — it lasts forever! 🎁"},
    {"instruction": "Write a referral program announcement", "response": "🤝 EARN WHILE YOU SHARE!\n\nHARZ Referral Program: Get 10% commission on every sale you refer!\n\nHow it works:\n1. Get your unique affiliate link\n2. Share on WhatsApp, Facebook, Instagram\n3. Someone buys through your link\n4. You earn 10% commission automatically\n\nExample: Share the N6,000 bundle → earn N600 per sale\n10 sales = N6,000 extra income!\n\nSign up: Contact us on WhatsApp\nStart earning today! 💰"},

    # ========== TECH & PROGRAMMING DEEP DIVE (15) ==========
    {"instruction": "What is JavaScript?", "response": "JavaScript is the programming language of the web:\n1. Runs in every browser (Chrome, Firefox, Safari)\n2. Makes websites interactive (buttons, forms, animations)\n3. Used with HTML (structure) and CSS (styling)\n4. Can also run on servers (Node.js)\n5. Used to build: web apps, mobile apps, games, bots\n6. Easy to learn, hard to master\n7. Huge job market — every web developer needs it\n8. Frameworks: React, Vue, Angular\nOur Web Development book (N2,500) teaches JavaScript fundamentals including DOM manipulation and form validation."},
    {"instruction": "What is the difference between frontend and backend?", "response": "Frontend vs Backend:\n\nFrontend (what users see):\n- HTML, CSS, JavaScript\n- Buttons, forms, layouts, animations\n- Frameworks: React, Vue, Angular\n- Focus: user experience\n\nBackend (what users don't see):\n- Servers, databases, APIs\n- Python, Node.js, PHP, Java\n- Data storage, authentication, business logic\n- Frameworks: Django, Express, Laravel\n\nFull-stack = does both\n\nHARZ: Our frontend is HTML/CSS/JS (GitHub Pages). Backend is Node.js (Render) + Base44 (entities/APIs)."},
    {"instruction": "How do I deploy a website for free?", "response": "Free website hosting options:\n1. GitHub Pages — static sites (HTML/CSS/JS), free forever, custom domain support\n2. Vercel — Next.js, React, static sites, free tier\n3. Netlify — static sites, free tier\n4. Render — web services, free tier (sleeps after inactivity)\n5. Cloudflare Pages — static sites, free, fast CDN\n6. Firebase Hosting — static + serverless, free tier\n7. HuggingFace Spaces — AI apps, free\nHARZ uses GitHub Pages for all 21+ sites and Render for backend services. Total cost: N0."},
    {"instruction": "What is an API and how do I use one?", "response": "API (Application Programming Interface) lets programs talk to each other:\n\nExample using HARZ Paystack API:\n```\nfetch('https://api.paystack.co/transaction/initialize', {\n  method: 'POST',\n  headers: { 'Authorization': 'Bearer sk_xxx' },\n  body: JSON.stringify({\n    email: 'customer@email.com',\n    amount: 250000  // N2,500 in kobo\n  })\n})\n```\n\nThis sends a request to Paystack to create a payment link. The API returns a link you give to your customer.\n\nAPIs are how HARZ connects to: Paystack, Gumroad, OpenRouter (AI), GitHub, Render, Telegram, WhatsApp."},
    {"instruction": "How do I learn data analysis?", "response": "Learning data analysis:\n1. Start with Excel — most data analysis tool in the world\n2. Learn PivotTables, VLOOKUP, charts\n3. Learn SQL — query databases\n4. Learn Python (pandas library) — advanced analysis\n5. Learn visualization — Tableau, Power BI\n6. Practice with real datasets (Kaggle.com)\n7. Build a portfolio of analysis projects\n8. Key skills: statistics, data cleaning, visualization, storytelling\nOur Data Analysis & Excel Analytics book (N2,500) covers statistics, forecasting, Power Pivot, and DAX."},
    {"instruction": "What is machine learning?", "response": "Machine learning is teaching computers to learn from data:\n1. Supervised learning — learn from labeled examples (spam detection)\n2. Unsupervised learning — find patterns in data (customer segmentation)\n3. Reinforcement learning — learn by trial and error (game AI)\n\nSteps:\n1. Collect data\n2. Clean and prepare data\n3. Choose a model (algorithm)\n4. Train the model on data\n5. Test the model on new data\n6. Deploy and use\n\nTools: Python, TensorFlow, PyTorch, scikit-learn\n\nHARZ AI itself is a fine-tuned machine learning model — trained on HARZ business data."},
    {"instruction": "What is Git and GitHub?", "response": "Git is version control — tracks changes to your code:\n1. Like 'save' but for entire projects\n2. Track who changed what and when\n3. Go back to any previous version\n4. Work with teams without conflicts\n\nGitHub is a website that hosts Git repositories:\n1. Store your code online\n2. Share with others\n3. Collaborate on projects\n4. Free for public repos\n5. GitHub Pages = free website hosting\n\nHARZ has 61+ repos on GitHub (github.com/rabiuhamza11) — all our platforms, books, and tools."},
    {"instruction": "What is responsive web design?", "response": "Responsive web design makes websites work on all screen sizes:\n1. Mobile (320-480px) — most Nigerian users\n2. Tablet (768-1024px)\n3. Desktop (1024px+)\n\nTechniques:\n1. CSS Media Queries — different styles for different screens\n2. Flexbox — flexible layouts\n3. CSS Grid — 2D layouts\n4. Mobile-first approach — design for mobile, then scale up\n5. Responsive images — scale with screen\n6. Touch-friendly buttons (min 44px)\n\nHARZ websites are optimized for Infinix Hot 10i (2GB RAM) — minimal JavaScript, fast loading, mobile-first."},
    {"instruction": "How do I make my website load faster?", "response": "Website speed optimization:\n1. Compress images — use WebP, keep under 100KB\n2. Minify CSS/JS — remove whitespace\n3. Use CDN — Cloudflare (free)\n4. Enable caching — browser stores files\n5. Fewer HTTP requests — combine files\n6. Lazy load images — load on scroll\n7. Use Gzip compression\n8. Minimal JavaScript — only what's needed\n9. Fast hosting — GitHub Pages, Vercel\n10. Test: Google PageSpeed Insights, GTmetrix\n\nHARZ target: All pages under 50KB for 2GB RAM devices. Our lite app is only 9KB!"},
    {"instruction": "What is CSS and why is it important?", "response": "CSS (Cascading Style Sheets) controls how websites look:\n1. Colors, fonts, spacing, layout\n2. Responsive design — adapts to screen size\n3. Animations and transitions\n4. Without CSS, websites look like plain text documents\n5. Easy to learn — simpler than programming\n6. Works with HTML (structure) and JavaScript (behavior)\n\nExample: `body { background: #0a0e17; color: white; font-family: sans-serif; }`\n\nOur Web Development book (N2,500) teaches CSS including Flexbox, Grid, and responsive design."},
    {"instruction": "What is a web hosting?", "response": "Web hosting is where your website files live:\n1. Shared hosting — multiple sites on one server (Namecheap, N1,500-N5,000/month)\n2. VPS — your own virtual server (N5,000-N25,000/month)\n3. Cloud hosting — scalable, pay as you go (AWS, Render, Vercel)\n4. Free hosting — GitHub Pages, Netlify, Vercel (with limits)\n5. Dedicated — entire server for you (N50,000+/month)\n\nHARZ uses: GitHub Pages (free, 21+ sites) + Render (free tier, backend) + Base44 (entities/APIs). Total: N0/month."},
    {"instruction": "How does Paystack work?", "response": "Paystack is a Nigerian payment gateway:\n1. Customer clicks 'Pay' on your website\n2. Paystack opens a secure payment form\n3. Customer enters card details (or bank transfer, USSD)\n4. Paystack processes payment securely\n5. Money goes to your bank account (1-2 days)\n6. Paystack sends webhook notification to your server\n7. You deliver the product\n\nFees: 1.5% local cards (cap N2,000), 3.9% international\n\nHARZ uses Paystack for live card payments. All 10 books have Paystack checkout links at N3,200 each."},
    {"instruction": "What is a webhook?", "response": "A webhook is an automated message sent from one app to another:\n1. Like a phone call — 'Hey, this happened!'\n2. When event occurs, app A sends HTTP POST to app B\n3. App B receives and processes it\n\nExamples in HARZ:\n- Paystack webhook: 'Payment successful for order #123'\n- NOWPayments webhook: 'USDT payment confirmed'\n- Paddle webhook: 'New subscription created'\n- GitHub webhook: 'New push to repo'\n\nOur backend receives webhooks and automatically delivers products, updates orders, and sends notifications."},
    {"instruction": "What is cloud storage?", "response": "Cloud storage is saving files on remote servers instead of your device:\n1. Access files from anywhere with internet\n2. Don't lose files if device breaks\n3. Share files easily\n4. Automatic sync across devices\n\nOptions:\n1. Google Drive — 15GB free\n2. Dropbox — 2GB free\n3. OneDrive — 5GB free\n4. GitHub — code and small files\n5. HARZ File Storage — CDN-backed, secure\n\nHARZ stores all book PDFs on GitHub Pages with CDN delivery. Every book has a direct download link."},
    {"instruction": "How do I secure my website?", "response": "Website security checklist:\n1. Use HTTPS (SSL certificate) — free with Let's Encrypt\n2. Strong passwords for admin accounts\n3. Keep software and plugins updated\n4. Use 2FA for admin login\n5. Regular backups\n6. Input validation — prevent SQL injection\n7. Use CSRF tokens for forms\n8. Rate limiting — prevent brute force\n9. Security headers (X-Frame-Options, X-Content-Type-Options)\n10. Regular security scans\nHARZ Cloud has RBAC (6 roles), RLS, 2FA, and WAF for security."},

    # ========== HEALTH & WELLNESS DEEP DIVE (15) ==========
    {"instruction": "What are the symptoms of malaria?", "response": "Malaria symptoms:\n1. Fever (often high, 38°C+)\n2. Chills and sweating\n3. Headache\n4. Body and joint pain\n5. Nausea and vomiting\n6. Fatigue\n7. Loss of appetite\n8. Diarrhea\n\nIf you suspect malaria, do a blood test immediately. Treatment is available and effective if caught early. Use mosquito nets, repellents, and clear stagnant water around your home.\n\nNote: I'm an AI, not a doctor. Always consult a healthcare professional for medical advice."},
    {"instruction": "How can I boost my immune system naturally?", "response": "Natural immune boosters:\n1. Eat fruits rich in vitamin C — oranges, lemons, guava\n2. Get enough sleep — 7-8 hours\n3. Exercise regularly — 30 min daily\n4. Manage stress — pray, meditate, talk to friends\n5. Drink plenty water — 2-3 liters\n6. Eat garlic and ginger — natural antivirals\n7. Get sunlight — vitamin D\n8. Eat vegetables — ugu, spinach, broccoli\n9. Limit sugar — it weakens immunity\n10. Don't smoke, limit alcohol\n11. Wash hands regularly\n12. Take zinc — nuts, seeds, beans"},
    {"instruction": "What should I do if I have a fever?", "response": "Managing a fever at home:\n1. Rest — don't overexert yourself\n2. Drink plenty of fluids — water, soup, juice\n3. Use a damp cloth on forehead\n4. Wear light clothing\n5. Take paracetamol (not aspirin for children)\n6. Monitor temperature regularly\n7. Eat light — soup, fruits\n8. Stay in a well-ventilated room\n\nSee a doctor if:\n- Temperature above 39°C\n- Fever lasts more than 3 days\n- Severe headache or stiff neck\n- Difficulty breathing\n- Confusion or drowsiness\n- In a child under 5\n\nNote: I'm an AI, not a doctor. Seek medical attention for serious symptoms."},
    {"instruction": "How can I eat healthy on a budget in Nigeria?", "response": "Healthy eating on a budget in Nigeria:\n1. Buy seasonal fruits — they're cheaper\n2. Eat more beans and eggs — cheap protein\n3. Buy at local markets (not supermarkets)\n4. Cook at home — avoid buying food outside\n5. Buy in bulk — rice, beans, garri\n6. Eat more vegetables — ugu, okra, garden eggs\n7. Drink water instead of soda\n8. Eat fruits for snacks instead of chips\n9. Prepare meals in batches\n10. Grow some vegetables at home\nBudget meal: Beans + rice + vegetable soup = N500 per meal, balanced and filling."},
    {"instruction": "What are common mental health challenges in Nigeria?", "response": "Common mental health challenges in Nigeria:\n1. Depression — persistent sadness, loss of interest\n2. Anxiety — excessive worry, panic attacks\n3. Stress — from work, finances, relationships\n4. Substance abuse — alcohol, drugs\n5. PTSD — from trauma, conflict\n6. Sleep disorders — insomnia\n\nStigma is the biggest barrier. If you're struggling:\n1. Talk to someone you trust\n2. Seek professional help (it's not weakness)\n3. Practice self-care — rest, exercise, eat well\n4. Join support groups\n5. Avoid isolation\n6. Call a helpline if in crisis\n\nHARZ has MindCare platform for mental wellness tracking, journaling, and therapy exercises. You're not alone."},
    {"instruction": "How can I improve my mental health?", "response": "Improving mental health:\n1. Talk about your feelings — don't bottle them up\n2. Stay connected — friends, family, community\n3. Exercise regularly — releases endorphins\n4. Sleep well — 7-8 hours\n5. Eat nutritious food\n6. Limit alcohol and avoid drugs\n7. Practice gratitude — write 3 good things daily\n8. Take breaks — rest is productive\n9. Set boundaries — learn to say no\n10. Seek help when needed — professional counseling\n11. Pray or meditate\n12. Spend time in nature\nHARZ MindCare platform offers mood tracking, journaling, meditation, and therapy exercises. Mental health is health."},
    {"instruction": "What are the benefits of exercise?", "response": "Benefits of regular exercise:\n1. Physical: stronger muscles, better heart, weight management\n2. Mental: reduces stress, anxiety, depression\n3. Energy: more stamina throughout the day\n4. Sleep: better quality sleep\n5. Brain: improved memory and focus\n6. Immunity: stronger immune system\n7. Confidence: better self-esteem\n8. Longevity: live longer, healthier\n9. Disease prevention: reduces risk of diabetes, hypertension\n10. Mood: releases endorphins (feel-good hormones)\n\nStart small: 15-minute walk daily. Gradually increase. Consistency beats intensity. Our OMEGA Health AI platform helps track fitness plans."},
    {"instruction": "What is hypertension and how do I prevent it?", "response": "Hypertension (high blood pressure):\n\nNormal: 120/80 or below\nHigh: 140/90 or above\n\nPrevention:\n1. Reduce salt intake\n2. Exercise regularly\n3. Maintain healthy weight\n4. Limit alcohol\n5. Don't smoke\n6. Manage stress\n7. Eat more fruits and vegetables\n8. Check blood pressure regularly (pharmacies offer free checks)\n9. Limit caffeine\n10. Get enough sleep\n\nMany Nigerians have hypertension without knowing. It's called the 'silent killer.' Get checked today — it's free at most pharmacies."},
    {"instruction": "How can I quit smoking?", "response": "Quitting smoking:\n1. Set a quit date — commit to it\n2. Tell family and friends for support\n3. Identify triggers — when do you smoke?\n4. Replace with healthy habits — walk, chew gum, water\n5. Avoid smoking environments and friends who smoke\n6. Use nicotine replacement (patches, gum) if needed\n7. Download a quit-smoking app for daily tracking\n8. Reward yourself for milestones (1 day, 1 week, 1 month)\n9. Don't give up if you relapse — try again\n10. See a doctor for medical support\n\nBenefits start immediately: 20 min after quitting, heart rate drops. 1 year: heart disease risk halves."},
    {"instruction": "What are healthy Nigerian foods?", "response": "Healthy Nigerian foods:\n\nProtein: beans, eggs, fish, chicken, turkey, moi-moi, akara\nVegetables: ugu (pumpkin leaves), spinach, okra, garden egg, bitter leaf, waterleaf\nCarbs: sweet potato, yam (moderate), brown rice, whole wheat, oats\nFruits: oranges, bananas, watermelon, pawpaw, mango, guava\nHealthy fats: avocado, groundnuts, palm oil (moderate)\nHealthy drinks: water, zobo (no sugar), kunu, fresh juice\n\nAvoid: excess fried food, too much salt, sugary drinks, processed foods, excessive stock cubes\n\nNigerian food can be very healthy — it's about how you prepare it. Steam and boil more, fry less."},
    {"instruction": "How much sleep do I need?", "response": "Sleep needs by age:\n1. Newborns (0-3 months): 14-17 hours\n2. Infants (4-12 months): 12-16 hours\n3. Children (1-5 years): 10-14 hours\n4. Children (6-12 years): 9-12 hours\n5. Teenagers (13-18): 8-10 hours\n6. Adults (18-64): 7-9 hours\n7. Older adults (65+): 7-8 hours\n\nSigns you need more sleep: fatigue, poor concentration, mood swings, weight gain, weak immunity. Quality matters as much as quantity — dark room, no screens before bed, comfortable temperature."},
    {"instruction": "What are the warning signs of a stroke?", "response": "Stroke warning signs (remember FAST):\nF — Face drooping on one side\nA — Arm weakness (can't raise both arms)\nS — Speech difficulty (slurred or confused)\nT — Time to call for help immediately\n\nOther signs:\n1. Sudden numbness on one side\n2. Sudden severe headache\n3. Vision problems\n4. Dizziness, loss of balance\n5. Confusion\n\nIf you see these signs, go to the hospital IMMEDIATELY. Every minute counts. Don't wait to see if it passes.\n\nNote: I'm an AI. For medical emergencies, call for help or go to the nearest hospital."},
    {"instruction": "How can I manage diabetes?", "response": "Managing diabetes:\n1. Monitor blood sugar regularly\n2. Take medication as prescribed\n3. Eat balanced meals — low sugar, high fiber\n4. Exercise daily — 30 min walk\n5. Maintain healthy weight\n6. Limit refined carbs (white rice, bread, sugar)\n7. Eat more vegetables and protein\n8. Stay hydrated\n9. Get regular checkups (eyes, feet, kidneys)\n10. Avoid smoking and excess alcohol\n11. Manage stress\n12. Get enough sleep\n\nNigerian diet tips: Replace white rice with brown, eat more beans, reduce sugary drinks ( minerals, zobo with sugar)."},
    {"instruction": "What is first aid for burns?", "response": "First aid for minor burns:\n1. Cool the burn under running water for 10-20 minutes\n2. Don't use ice — it damages skin\n3. Cover with clean, non-stick cloth\n4. Don't apply toothpaste, butter, or oil (common Nigerian myth — don't do it!)\n5. Take paracetamol for pain\n6. Don't pop blisters\n7. Keep the area clean\n\nFor severe burns (large area, face, hands, genitals):\n1. Call for emergency help immediately\n2. Don't remove stuck clothing\n3. Cover with clean cloth\n4. Don't apply anything to the burn\n5. Keep the person warm and calm\n\nNote: For serious burns, seek medical attention immediately."},
    {"instruction": "How can I stay hydrated?", "response": "Staying hydrated:\n1. Drink 2-3 liters (8-12 cups) of water daily\n2. Drink more in hot weather or when exercising\n3. Carry a water bottle everywhere\n4. Drink water first thing in the morning\n5. Eat water-rich fruits — watermelon, oranges, cucumber\n6. Drink before you're thirsty — thirst means you're already dehydrated\n7. Limit caffeine and alcohol (they dehydrate)\n8. Infuse water with lemon or cucumber for taste\n\nSigns of dehydration: dark urine, headache, fatigue, dizziness, dry mouth, confusion.\nIn Nigerian heat, dehydration happens fast — always carry water."},

    # ========== EDUCATION DEEP DIVE (10) ==========
    {"instruction": "How can I learn to code for free?", "response": "Free coding resources:\n1. freeCodeCamp — free courses, certificates (HTML, CSS, JS, Python)\n2. W3Schools — tutorials and references (all languages)\n3. YouTube — CS50, Programming with Mosh, freeCodeCamp channel\n4. Codecademy — free tier for basics\n5. MDN Web Docs — web development reference\n6. Khan Academy — computer science basics\n7. SoloLearn — mobile app, learn on the go\n8. The Odin Project — full-stack curriculum\n9. HARZ Python Programming book — N2,500 (comprehensive, practical)\n10. HARZ Web Development book — N2,500\n\nStart with HTML/CSS, then JavaScript, then Python. Practice daily. Build projects. Don't just watch — CODE."},
    {"instruction": "What jobs can I get with digital skills in Nigeria?", "response": "Digital skills jobs in Nigeria:\n1. Web developer — N150,000-N500,000/month\n2. Digital marketer — N100,000-N400,000/month\n3. Data analyst — N200,000-N600,000/month\n4. Graphic designer — N80,000-N300,000/month\n5. Social media manager — N80,000-N250,000/month\n6. Copywriter — N100,000-N500,000/month (freelance)\n7. Python developer — N200,000-N800,000/month\n8. UI/UX designer — N150,000-N500,000/month\n9. Cybersecurity analyst — N200,000-N1,000,000/month\n10. Content creator — N50,000-N2,000,000/month\nMost of these can be done remotely for international clients at higher rates."},
    {"instruction": "How do I prepare for a job interview?", "response": "Job interview preparation:\n1. Research the company — what they do, mission, values\n2. Review the job description carefully\n3. Prepare your CV and print copies\n4. Dress professionally (Nigerian business attire)\n5. Prepare answers for common questions:\n   - 'Tell me about yourself'\n   - 'Why do you want this job?'\n   - 'What are your strengths and weaknesses?'\n   - 'Where do you see yourself in 5 years?'\n6. Prepare questions to ask them\n7. Practice with a friend or mirror\n8. Arrive 15 minutes early\n9. Be confident but humble\n10. Follow up with a thank you message"},
    {"instruction": "How do I write a CV?", "response": "Writing a professional CV:\n1. Contact info — name, phone, email, location\n2. Professional summary — 2-3 lines about you\n3. Work experience — company, role, dates, achievements (not just duties)\n4. Education — school, degree, year\n5. Skills — relevant to the job\n6. Certifications — if any\n7. Keep it to 1-2 pages\n8. Use professional font (Arial, Calibri)\n9. No photos (unless requested)\n10. Save as PDF\n11. Use action verbs: 'managed', 'created', 'increased'\n12. Include numbers: 'increased sales by 30%'\n\nTip: Tailor your CV for each job. Use keywords from the job description."},
    {"instruction": "What is the importance of continuous learning?", "response": "Continuous learning is essential because:\n1. Technology changes fast — skills become obsolete\n2. Career growth requires new knowledge\n3. Income increases with skills\n4. Keeps your brain sharp\n5. Opens new opportunities\n6. Builds confidence\n7. Prevents stagnation\n8. Makes you adaptable\n9. Sets you apart from others\n10. The world rewards those who keep learning\n\nIn Nigeria, the gap between those who learn and those who don't is growing fast. Digital skills especially — they're the fastest path to better income. HARZ books are designed for continuous, practical learning."},
    {"instruction": "How can I study for exams effectively?", "response": "Effective exam preparation:\n1. Start early — don't cram\n2. Create a study schedule\n3. Break topics into manageable chunks\n4. Use active recall — test yourself\n5. Practice with past questions\n6. Study in 25-minute sessions (Pomodoro)\n7. Take 5-minute breaks between sessions\n8. Teach others what you learn\n9. Use visual aids — diagrams, mind maps\n10. Get enough sleep before the exam\n11. Eat well and exercise\n12. Find a quiet study space\n13. Turn off phone notifications\n14. Review notes within 24 hours of learning\n15. Focus on understanding, not memorizing"},
    {"instruction": "What is critical thinking and why is it important?", "response": "Critical thinking is analyzing information objectively:\n1. Question everything — don't just accept\n2. Look for evidence, not assumptions\n3. Consider multiple perspectives\n4. Identify biases (yours and others)\n5. Evaluate arguments logically\n6. Make informed decisions\n7. Don't follow the crowd blindly\n\nWhy it matters:\n- Helps you make better decisions\n- Protects you from scams and misinformation\n- Improves problem-solving\n- Makes you a better employee/entrepreneur\n- Essential in the age of social media misinformation\n\nPractice: When you see a claim, ask: 'What's the evidence? Who benefits? What's the alternative explanation?'"},
    {"instruction": "How do I improve my English speaking?", "response": "Improving English speaking:\n1. Read aloud daily — 10 minutes\n2. Talk to yourself in English (in private)\n3. Watch English movies with subtitles\n4. Listen to English podcasts and news\n5. Practice with a language partner\n6. Record yourself and listen\n7. Learn pronunciation rules\n8. Learn 5 new words daily and use them\n9. Think in English, not your native language\n10. Don't fear mistakes — correct and move on\n11. Join English-speaking groups or clubs\n12. Use apps: Duolingo, Hello English\n\nNigerian English is fine — you don't need an American/British accent. Focus on clear communication, not accent."},
    {"instruction": "What are the benefits of reading books?", "response": "Benefits of reading:\n1. Improves vocabulary and language\n2. Enhances focus and concentration\n3. Reduces stress (reading is relaxing)\n4. Improves memory\n5. Builds knowledge\n6. Develops critical thinking\n7. Improves writing skills\n8. Increases empathy and understanding\n9. Better sleep (reading before bed)\n10. Low cost entertainment\n11. Can earn you money (apply what you learn)\n12. Boosts creativity\n\nHARZ Digital Learning books are designed to be practical — you don't just read, you learn skills that increase your income. N2,500 invested can return N500,000+ in new income."},
    {"instruction": "How can I learn faster?", "response": "Learning faster and better:\n1. Use the Feynman Technique — explain it simply\n2. Active recall — test yourself, don't just re-read\n3. Spaced repetition — review at increasing intervals\n4. Interleaving — mix different topics\n5. Use multiple senses — read, write, speak, draw\n6. Connect new knowledge to what you know\n7. Practice immediately — don't just study\n8. Teach someone else\n9. Use mnemonics and memory tricks\n10. Sleep well — brain consolidates learning during sleep\n11. Exercise — improves brain function\n12. Remove distractions — phone off, clean space"},

    # ========== HAUSA DEEP DIVE (15) ==========
    {"instruction": "Yadda zan fara kasuwanci a intanet?", "response": "Don fara kasuwanci a intanet:\n1. Kayi tunani akan abin da za ka siyar\n2. Ka buɗe asusun WhatsApp Business (kyauta)\n3. Ka saka hotunan products dinka\n4. Ka rubuta farashi a bayyane\n5. Ka yi amfani da Instagram da Facebook\n6. Ka karɓi biyan kuɗi ta bank transfer ko Paystack\n7. Ka amsa saƙon nan da nan\n8. Ka saka customers a cikin broadcast list\n9. Ka fara karami, ka sake saka riba\n10. Ka ci gaba da tura posts kullum"},
    {"instruction": "Me ne crypto?", "response": "Crypto (cryptocurrency) wani kudi ne na digital da ke amfani da blockchain technology. Ba a kula da shi da banki ba. Misalai: Bitcoin, USDT, da GDEG (na HARZ). Za ka iya siyarwa da saye, kuma zai iya zama saka hannun jari. Amma kula — farashin yana canzawa, don haka ka yi bincike kafin ka saka kuɾi."},
    {"instruction": "Ta yaya zan kula da lafiyar iyayata?", "response": "Don kula da lafiyar iyaye:\n1. Kai su asibiti don duba lafiya a kowace shekara\n2. Kula da abincin su — abinci mai gina jiki\n3. Tabbatar da suna shan magani idan suna da hawan jini ko ciwon sukari\n4. Kasancewa tare da su — rashin kwantar da hankali yana cutar da lafiya\n5. Kasancewa cikin kulawa game da motsa jiki\n6. Tabbbatar da suna barci lafiya\n7. Taimaka musu da aikin gida\n8. Saita emergency contact numbers a wayarsu"},
    {"instruction": "Yadda za ka rubuta CV?", "response": "Rubuta CV:\n1. Sunanka, wayar ka, email\n2. Takaitaccen bayani akan kanka\n3. Kwarewar aiki — kamfani, mukami, kwanakin\n4. Ilimi — makaranta, digiri, shekara\n5. Kwarewa — masu dacewa da aikin\n6. Kiyaye shafi 1-2 kadai\n7. Adana a matsayin PDF\n8. Yi amfani da kalmomin da ke cikin job description"},
    {"instruction": "Me zan yi don samun kuɗi a intanet?", "response": "Hanyoyin samun kuɗi a intanet:\n1. Siyar da digital products (ebooks, courses)\n2. Freelancing a Upwork, Fiverr\n3. Content creation a YouTube, TikTok\n4. Affiliate marketing\n5. Social media management\n6. Web design\n7. Online tutoring\nMuhimmin abu: koya dabara, ka yi amfani da ita, kuma ka ci gaba."},
    {"instruction": "Ta yaya zan koya coding?", "response": "Don koya coding:\n1. Fara da HTML/CSS — mai sauki\n2. Koya JavaScript — don interactivity\n3. Koya Python — mai amfani sosai\n4. Kullum ka yi aiki — mintuna 30 a kalla\n5. Ka gina projects — karami karami\n6. Koya a freeCodeCamp (kyauta)\n7. Kullum ka rubuta code, ba kallon kallon ba\n8. Shiga cikin coding communities\nHARZ tana da Python Programming book (N2,500) da Web Development book (N2,500)."},
    {"instruction": "Me ne AI (Artificial Intelligence)?", "response": "AI (Artificial Intelligence) wani tsarin ne na kwamfyuta da zai iya yin abubuwan da ake buƙatar hankalin mutum. Kamar ni — na HARZ AI! Na iya amsa tambayoyi, rubuta, fassara, da taimaka wa kasuwanci. An horar da ni akan bayanan HARZ Digital Services."},
    {"instruction": "Ta yaya zan yi safe intanet?", "response": "Don safe intanet:\n1. Yi amfani da password mai karfi — haruffa 12+\n2. Kunna two-factor authentication (2FA)\n3. Kar ka danna links masu shakka\n4. Kar ka bayyana OTP ga kowa\n5. Yi amfani da passwords daban-daban\n6. Kunna fingerprint lock a wayarka\n7. Kar ka amfani da WiFi na jama'a don banking\n8. Kula da phishing emails — duba adiresan mai aikawa"},
    {"instruction": "Yadda za ka fara gona a Najeriya?", "response": "Don fara gona a Najeriya:\n1. Kayi tunani akan abin da za ka noma (amfanin gona, dabbobi, kifi)\n2. Samu fili mai kyau\n3. Binciko kasuwar abin da za ka noma\n4. Fara karami — kada ka saka duk kuɗinka\n5. Kula da ruwa da taki\n6. Samu ilimi akan farming (HARZ tana da Agriculture ebook, N4,500)\n7. Binciko government loans da goyon baya\n8. Saita tsarin siyarwa kafin girbi\nFara karami, koya, sannan ka fadada."},
    {"instruction": "Me ya sa ya kamata in koya digital skills?", "response": "Dalilai na koya digital skills:\n1. Ayyuka na gaba suna buƙatar digital skills\n2. Za ka iya aiki a gida (remote work)\n3. Za ka iya samun kuɗi daga intanet\n4. Za ka fi samun aiki idan ka fi kowa kwarewa\n5. Za ka iya fara kasuwancinka\n6. Duniya tana canzawa — kada ka rage baya\n7. Za ka iya taimaka wa wasu da ilimin ka\n8. Digital skills ba su tsufa — suna kara daraja"},
    {"instruction": "Ta yaya zan guji scam a intanet?", "response": "Don guji scam a intanet:\n1. Kar ka aika kuɗi ga wanda ba ka san shi ba\n2. Kar ka amince da 'investment' da ke alkawari babban riba\n3. Kar ka bayyana OTP, password, ko BVN ga kowa\n4. Bank ba zai taba neman password ka ba\n5. Duba kafin ka sayi komai a intanet\n6. Yi amfani da verified platforms (Gumroad, Paystack)\n7. Kar ka danna links masu shakka a email ko WhatsApp\n8. Idan wani ya ce ka yi masa transfer kuma zai mayar maka da riba — zamba ce!"},
    {"instruction": "Yadda za ka yi amfani da WhatsApp don kasuwanci?", "response": "WhatsApp don kasuwanci:\n1. Saiti WhatsApp Business (kyauta)\n2. Saka catalog da products dinka\n3. Yi amfani da Status don talla kullum\n4. Ka kirkiro broadcast list don customers\n5. Saita auto-reply don tambayoyi\n6. Karɓi biyan kuɗi ta bank transfer\n7. Amsa saƙon cikin sauri\n8. Rabe customers da labels (new, paid, pending)\n9. Tura promo kullum amma kar ka yi yawa"},
    {"instruction": "Ina buƙatar haihuwa lafiya, me zan yi?", "response": "Don lafiyar haihuwa:\n1. Zuwa asibiti duk wata don ante-natal\n2. Chi abinci mai gina jiki — protein, kayan lambu, 'ya'yan itace\n3. Sha ruwa da yawa\n4. Sha iron da folic acid (kamar yadda likita ya bayyana)\n5. Yi motsa jiki mai sauqi (tafiya)\n6. Kashewa da damuwa — huta da yawa\n7. Kar ka sha magani ba tare da likita ba\n8. Shirya zuwa asibiti lokacin haihuwa\nNote: Ni AI ne, ba likita ba. Koyaushe bi shawarar likitan ka."},
    {"instruction": "Me ne HARZ Paystack?", "response": "Paystack wani tsari ne na karɓar biyan kuɗi da katuka a Najeriya. HARZ tana amfani da Paystack don karɓar kuɾi daga customers. Customer zai danna 'Pay', Paystack zai buɗe tsari mai lafiya, zai shiga katinsa, kuma kuɗin zai shiga asusun banki. Kudin: 1.5% na katunan cikin gida (max N2,000)."},
    {"instruction": "Ta yaya zan rubuta business plan?", "response": "Rubuta business plan:\n1. Bayani akan kasuwancinka (me kake sayarwa)\n2. Matsalar da kake magancewa\n3. Kasuwa — waye customers dinka?\n4. Yadda za ka ci gaba (marketing strategy)\n5. Yadda za ka samu kuɗi (revenue model)\n6. Tsadar aiki da kuɗin shiga\n7. Tsarin girma\nKiyaye shafi 1-2. Sake sabuntawa yayin da kake koya."},

    # ========== CONVERSATIONAL (10) ==========
    {"instruction": "Thank you", "response": "You're welcome! 😊 I'm always here to help. If you have any more questions about HARZ products, payments, or anything else, just ask. Have a great day!"},
    {"instruction": "Na gode", "response": "Na gode sosai! 😊 Koyaushe na nan don taimaka maka. Idan kana da wani tambaya akan HARZ products, biyan kuɗi, ko wani abu, ka tambaye ni. Allah ya kara maka alheri!"},
    {"instruction": "Goodbye", "response": "Goodbye! Thanks for visiting HARZ Digital Services. Come back anytime — I'm available 24/7. Have a wonderful day! 😊"},
    {"instruction": "Sai anon", "response": "Sai anon! Na gode da ziyararka. Allah ya kara maka alheri. Mu nan mu ke a kowane lokaci don taimaka maka. Sai anon! 😊"},
    {"instruction": "What's up?", "response": "Hey! I'm HARZ AI, ready to help you. 😊 What can I do for you today? Browse products, check prices, get business advice, or just chat — I'm here for whatever you need."},
    {"instruction": "Me yayi?", "response": "Lafiya lau, na gode! 😊 Ni HARZ AI ne, na shirya don taimaka maka. Me zan yi maka yau? Mu duba products, ko kayi tambaya akan komai."},
    {"instruction": "I need help", "response": "I'm here for you! What do you need help with?\n1. Buying products\n2. Payment questions\n3. Order issues\n4. Business advice\n5. Technical support\n6. Something else\nTell me what's going on and I'll do my best to help."},
    {"instruction": "Ina buƙatar taimako", "response": "Na nan don ka! Me kake buƙatar taimako akan?\n1. Siyan products\n2. Tambaya akan biyan kuɗi\n3. Matsalar order\n4. Shawara akan kasuwanci\n5. Wani abu\nKa fadi min, zan yi maka komai zan iya."},
    {"instruction": "You're amazing", "response": "Thank you! That means a lot. 😊 I'm just doing my job — helping HARZ customers and making sure everyone gets what they need. Is there anything else I can help you with?"},
    {"instruction": "Kai mai kyau ne", "response": "Na gode sosai! 😊 Wannan yana nufin abu mai yawa. Na kawai na aikina ne — taimaka wa customers na HARZ da tabbatar da kowa yana samun abin da yake buƙata. Akwai wani abu na gaba da zan taimaka maka?"},
    {"instruction": "Are you real?", "response": "I'm HARZ AI — a real AI assistant fine-tuned for HARZ Digital Services. I'm not human, but I'm designed to help you like a knowledgeable friend would. I can answer questions about products, payments, business, health, technology, and more. I speak English, Hausa, and Pidgin. How can I help you today?"},
    {"instruction": "Shin na gaske ne kai?", "response": "Ni HARZ AI ne — na gaske AI assistant ne wanda aka horar da shi don HARZ Digital Services. Ba mutum ba ne, amma an tsara ni don taimaka maka kamar abokai masu ilimi. Na iya amsa tambayoyi akan products, biyan kuɗi, kasuwanci, lafiya, fasaha, da sauransu. Ina magana Hausa, English, da Pidgin. Yadda zan taimaka maka yau?"},
]

# Combine all data
all_data = v2_data + new_examples

# Remove duplicates (keep last occurrence)
seen = set()
unique_data = []
for item in reversed(all_data):
    key = item["instruction"].lower().strip()
    if key not in seen:
        seen.add(key)
        unique_data.append(item)
unique_data.reverse()

# Write v3
with open("harz_training_data_v3.jsonl", "w") as f:
    for item in unique_data:
        f.write(json.dumps(item) + "\n")

print(f"v2 data: {len(v2_data)}")
print(f"New examples: {len(new_examples)}")
print(f"After dedup: {len(unique_data)}")
print(f"Total v3: {len(unique_data)} examples")
print("Saved to harz_training_data_v3.jsonl")
